"""One-time source reconstruction; normal builds DO NOT read reference payloads.

Uses SkoolKit's canonical Z80 decoder for control-flow discovery. Unclassified
bytes remain explicit DEFB source, never INCBIN. Regeneration requires --force
once source exists so later manual annotations are not silently discarded.
"""
import argparse
import json
import re
import sys
from collections import deque
from pathlib import Path
from types import SimpleNamespace
from tape import ROOT, ANALYSIS_DEPS, reference, sha, describe, REFERENCE_SHA256
from analyze_ship_blueprints import analysis as analyze_ship_blueprints, render_asm as render_ship_blueprints
from analyze_ship_blueprints import text_dispatch_targets, write_variant_sources
from analyze_ship_blueprints import TABLE_ADDRESS
from font_variant import PATCH_SOURCE, PATCH_SHA256, patch_font, fixed_font
from verified_annotations import ANNOTATIONS

sys.path.insert(0, str(ANALYSIS_DEPS))
try:
    from skoolkit.disassembler import Disassembler
except ImportError:
    raise SystemExit('Run tools\\install_analysis_tools.bat first (only needed for analysis, not builds).')

BASE = 0x6048
ENTRY = 0x7000
SOURCE = ROOT / 'src'

def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='ascii', newline='\n')

def bytes_line(data):
    return 'defb ' + ','.join(f'${b:02X}' for b in data)

def prologue(block, data, source='assets/Elite - 128k.tap', tape_sha256=REFERENCE_SHA256):
    return [
        f'; Reconstructed from {source}; no original binary is included at build time.',
        f'; TAP SHA256: {tape_sha256}',
        f'; Zero-based TAP data block {block}; payload SHA256: {sha(data)}',
        '; Generated by tools/bootstrap_sources.py. Normal builds assemble this file directly.',
        ''
    ]

def basic(data):
    lines = prologue(1, data) + ['org 0', 'BasicProgram:']
    pos = 0
    decoded = {
        5: 'SAVE "ELITE" LINE 10: VERIFY "": STOP',
        10: 'CLEAR 65535',
        15: 'BORDER 0: PAPER 0: INK 0: CLS',
        20: 'LOAD "" SCREEN$: PRINT AT 20,0;: LOAD "" CODE',
        30: 'RANDOMIZE USR 28672 ($7000)',
    }
    while pos < len(data):
        number = int.from_bytes(data[pos:pos+2], 'big')
        count = int.from_bytes(data[pos+2:pos+4], 'little')
        body = data[pos+4:pos+4+count]
        if len(body) != count or body[-1] != 13:
            raise ValueError('Invalid BASIC line')
        lines += ['', f'; {number} {decoded[number]}', f'BasicLine_{number}:',
                  f'    defb {number} >> 8,{number} & $FF',
                  f'    defw BasicLine_{number}_End - BasicLine_{number}_Body',
                  f'BasicLine_{number}_Body:']
        lines += ['    ' + bytes_line(body[i:i+16]) for i in range(0, count, 16)]
        lines += [f'BasicLine_{number}_End:']
        pos += 4 + count
    lines += ['', 'BasicProgramEnd:', f'assert BasicProgramEnd-BasicProgram = {len(data)}', '']
    write(SOURCE / 'basic.asm', '\n'.join(lines))

def screen(data):
    lines = prologue(3, data) + ['; Spectrum SCREEN$: 6144 bitmap bytes, then 768 attributes.',
                               '; Tape header says $8000; BASIC SCREEN$ overrides loading to $4000.',
                               'org 0', 'LoadingScreen:']
    for i in range(0, len(data), 16):
        if i == 6144:
            lines += ['LoadingScreenAttributes:']
        lines += ['    ' + bytes_line(data[i:i+16]) + f' ; screen offset ${i:04X}']
    lines += ['LoadingScreenEnd:', 'assert LoadingScreenAttributes-LoadingScreen = 6144',
              'assert LoadingScreenEnd-LoadingScreenAttributes = 768', '']
    write(SOURCE / 'screen.asm', '\n'.join(lines))

def graphics_regions(memory):
    """Read boundaries from the verified original LD operands, not guessed sizes."""
    def operand(address, opcode):
        if memory[address] != opcode:
            raise ValueError(f'Graphics landmark opcode changed at ${address:04X}')
        return memory[address+1] + 256*memory[address+2]

    font = operand(0x716B, 0x21)
    font_runtime = operand(0x716E, 0x11)
    font_size = operand(0x7171, 0x01)
    attributes = operand(0x7176, 0x21)
    attributes_runtime = operand(0x7179, 0x11)
    attributes_size = operand(0x717C, 0x01)
    bitmap = operand(0x743E, 0x21)
    bitmap_size = operand(0x7441, 0x01)
    bitmap_screen = operand(0x743B, 0x11)
    attributes_screen = operand(0x7446, 0x11)
    if (operand(0x7449,0x21),operand(0x744C,0x01)) != (attributes_runtime,attributes_size):
        raise ValueError('Cockpit attribute restore does not match startup copy')
    if (operand(0x8F47,0x11),operand(0x8F4A,0x21),operand(0x8F4D,0x01)) != (bitmap,bitmap_screen,bitmap_size):
        raise ValueError('Cockpit bitmap save and restore disagree')
    if (operand(0x8F52,0x11),operand(0x8F55,0x21),operand(0x8F58,0x01)) != (attributes_runtime,attributes_screen,attributes_size):
        raise ValueError('Cockpit attribute save and restore disagree')
    if operand(0xBB69,0x21) != font_runtime or memory[0xBB6C] != 0xD6:
        raise ValueError('Character lookup no longer uses the relocated font')
    first_code = memory[0xBB6D]
    glyph_height = memory[0xBBBC]
    if memory[0xBBBB] != 0x06 or glyph_height != 8 or font_size % glyph_height:
        raise ValueError('Character drawing is not a whole number of 8-row glyphs')
    if bitmap_size != 32*64 or attributes_size != 32*8:
        raise ValueError('Unexpected cockpit dimensions')
    regions = [
        dict(name='FontBitmap',file='font.asm',start=font,end=font+font_size,
             runtime=font_runtime,unit=glyph_height,first_code=first_code,
             comment='VERIFIED font: startup copies this block to FontRuntime; character lookup uses (code-FontFirstCode)*8.'),
        dict(name='CockpitAttributes',file='cockpit-attributes.asm',start=attributes,end=attributes+attributes_size,
             runtime=attributes_runtime,screen=attributes_screen,unit=32,
             comment='VERIFIED initial cockpit colours: 32 columns x 8 character rows. Copied to CockpitAttributesRuntime at startup.'),
        dict(name='CockpitBitmap',file='cockpit-bitmap.asm',start=bitmap,end=bitmap+bitmap_size,
             screen=bitmap_screen,unit=32,
             comment='VERIFIED initial cockpit bitmap: 256 x 64 pixels in Spectrum screen order. Copied to ScreenCockpitBitmap.'),
    ]
    constants = dict(FontRuntime=font_runtime,CockpitAttributesRuntime=attributes_runtime,
                     ScreenCockpitBitmap=bitmap_screen,ScreenCockpitAttributes=attributes_screen,
                     FontFirstCode=first_code,FontGlyphHeight=glyph_height)
    return regions,constants

def verified_data_regions(memory):
    """Return non-code regions supported by structure and runtime evidence."""
    if bytes(memory[0xA910:0xA917]) != b'JAMESON':
        raise ValueError('Default commander template moved or changed')
    if bytes(memory[0xD41B:0xD425]) != bytes.fromhex('DD2116A81168003EFFC9'):
        raise ValueError('104-byte active commander tape buffer reference changed')
    if bytes(memory[0x7C2D:0x7C39]) != bytes.fromhex('2110A91116A8016600EDB0C9'):
        raise ValueError('Initial commander template copy changed')
    if bytes(memory[0xD3E2:0xD3ED]) != bytes.fromhex('2116A81110A9016600EDB0'):
        raise ValueError('Commander tape working-copy update changed')
    for value in range(256):
        square = value * value
        if memory[0xBE00 + value] != square & 0xFF:
            raise ValueError('Low-byte square table changed')
        if memory[0xBF00 + value] != square >> 8:
            raise ValueError('High-byte square table changed')
    return [
        dict(name='InitialRuntimeState', file='initial-runtime-state.asm',
             start=BASE, end=0x6180, unit=16,
             comment='VERIFIED DATA: initial mutable game/object state; runtime access tracing records reads and writes here, never instruction fetches.'),
        dict(name='ShipBlueprintsAndDispatchTables', file='ship-blueprints-and-tables.asm',
             start=0x6180, end=ENTRY, unit=16,
             comment='VERIFIED DATA: structured ship geometry/blueprint records followed by in-image dispatch pointers; read at runtime and never executed.'),
        dict(name='EncodedTextData', file='encoded-text.asm',
             start=0x92B5, end=0x9966, unit=16,
             comment='VERIFIED DATA: zero-terminated game text with high-bit token bytes; text routines point into and read this block.'),
        dict(name='TextTokenDictionary', file='text-token-dictionary.asm',
             start=0x9A9D, end=0x9E74, unit=16,
             comment='VERIFIED DATA: token dictionary used to expand screen and message text; runtime reads cover this block.'),
        dict(name='ActiveCommanderRecord', file='active-commander-initial.asm',
             start=0xA816, end=0xA87E, unit=16,
             comment='VERIFIED DATA: mutable 104-byte commander buffer used directly by ROM tape load/save; the first 102 bytes follow the supplied save map.'),
        dict(name='CommanderTemplateBuffer', file='default-commander.asm',
             start=0xA910, end=0xA976, unit=16,
             comment='VERIFIED DATA: initial 102-byte JAMESON template; copied to ActiveCommanderRecord for a new game and reused as a mutable tape-workflow copy.'),
        dict(name='SquareLookupTables', file='square-tables.asm',
             start=0xBE00, end=0xC000, unit=256,
             comment='VERIFIED DATA: 256 low bytes then 256 high bytes of n*n for n=0..255.'),
    ]

def emit_verified_data(region, memory, labels, payload):
    start, end, name = region['start'], region['end'], region['name']
    lines = prologue(5, payload) + [
        f'; KNOWN DATA: ${start:04X}..${end-1:04X}, {end-start} bytes.',
        '; ' + region['comment'],
        '; Field-level names remain for later analysis where the exact format is not yet proved.',
        '',
    ]
    pc = start
    while pc < end:
        if pc in labels:
            if pc in ANNOTATIONS:
                comments = ANNOTATIONS[pc][1]
                lines += ['', '; VERIFIED: ' + comments[0]]
                lines += ['; ' + line for line in comments[1:]]
            lines += [labels[pc] + ':']
            if pc in ANNOTATIONS:
                lines += [f'L_{pc:04X}: ; legacy analysis alias; same address, no emitted bytes']
        if name == 'InitialRuntimeState' and labels.get(pc) == 'StationBlueprintPointer':
            # Original slot-zero pointer must match table entry zero. Emit a
            # symbol so the optional Adder layout relocates this instance too.
            if memory[pc:pc+2] != memory[TABLE_ADDRESS+1:TABLE_ADDRESS+3]:
                raise ValueError('Initial station pointer disagrees with Coriolis table entry')
            lines += ['    ; The persistent station bypasses the generic object/blueprint loader.',
                      '    defw ShipCoriolisStationBlueprint']
            pc += 2
            continue
        size = min(16, end - pc)
        while size > 1 and any(pc < address < pc + size for address in labels):
            size -= 1
        chunk = bytes(memory[pc:pc + size])
        text = ''.join(chr(value) if 32 <= value < 127 else '.' for value in chunk)
        lines += [f'    {bytes_line(chunk):<85} ; ${pc:04X} {text}']
        pc += size
    lines += ['', name + 'End:', f'defc {name}Size = {name}End - {name}',
              f'assert {name}Size = {end-start}', '']
    if name == 'InitialRuntimeState':
        lines[-1:] = ['assert StationBlueprintPointer-InitialRuntimeState = $23', '']
    write(SOURCE / 'data' / region['file'], '\n'.join(lines))

def emit_graphics(region, memory, labels, payload, provenance=None):
    start,end,name = region['start'],region['end'],region['name']
    lines = (prologue(5,payload) if provenance is None else provenance) + [
        f'; KNOWN DATA: ${start:04X}..${end-1:04X}, {end-start} bytes.',
        '; ' + region['comment'],
        '; The on-tape data is initial content, NOT read-only runtime storage.',
        '; The $C000..$CFFF area is later reused by graphics buffers and temporary stack.',
    ]
    if name == 'FontBitmap':
        lines += ['; One glyph per group, top-to-bottom rows, bit 7 is the leftmost pixel.',
                  '; Includes letters, digits and custom graphic tiles in punctuation slots.',
                  '; The five zero-filled slots after code $7A are NOT part of the startup copy.']
    elif name == 'CockpitBitmap':
        lines += ['; Source offset = ((y & 7) << 8) | ((y & $38) << 2) | (x >> 3).',
                  '; Local y=0..63 maps to physical screen y=128..191.',
                  '; This address also holds saved panel state or the second view-buffer half.']
    else:
        lines += ['; Each byte: FLASH bit 7, BRIGHT bit 6, PAPER bits 5..3, INK bits 2..0.',
                  '; Rows map to character rows 16..23 of the display.']
    pc=start
    while pc<end:
        offset=pc-start
        if offset % region['unit'] == 0:
            if name == 'FontBitmap':
                code=region['first_code']+offset//region['unit']
                lines += ['', f'; Character code ${code:02X} ({code}); source ${pc:04X}.']
            elif name == 'CockpitAttributes':
                lines += ['', f'; Character row {16+offset//32}.']
            else:
                y=((offset>>8)&7)|((offset>>2)&0x38)
                lines += ['', f'; Physical screen pixel row {128+y}.']
        if pc in labels: lines += [labels[pc]+':']
        size=1
        while size<16 and pc+size<end and (pc+size-start)%region['unit'] and pc+size not in labels:
            size+=1
        lines += ['    '+bytes_line(memory[pc:pc+size])+f' ; ${pc:04X}']
        pc+=size
    lines += ['',name+'End:',f'defc {name}Size = {name}End - {name}',
              f'assert {name}End-{name} = {end-start}']
    if name == 'FontBitmap':
        lines += ['defc FontGlyphCount = FontBitmapSize / FontGlyphHeight',
                  'defc FontRuntimeEnd = FontRuntime + FontBitmapSize',
                  'assert FontRuntimeEnd = GameLoadAddress',
                  'assert FontGlyphCount * FontGlyphHeight = FontBitmapSize',
                  f'assert FontFirstCode + FontGlyphCount = ${region["first_code"]+(end-start)//region["unit"]:02X}']
    write(SOURCE/'data'/region['file'],'\n'.join(lines)+'\n')

def image(data):
    end = BASE + len(data)
    memory = [0] * 65536
    memory[BASE:end] = data
    graphics_data, graphics_constants = graphics_regions(memory)
    known_data = verified_data_regions(memory) + graphics_data
    known_data.sort(key=lambda region: region['start'])
    config = SimpleNamespace(asm_hex=True, asm_lower=False, defb_size=16, defm_size=64, defw_size=8,
                             handle_rst=False, imaker=lambda a,o,b: SimpleNamespace(address=a,operation=o,data=b),
                             opcodes='', wrap=False)
    decoder = Disassembler(memory, config)
    pending = deque([ENTRY])
    code, owners, targets, conflicts = {}, {}, {ENTRY}, []
    # The two text dispatch entry points select these indirect code targets.
    text_targets = text_dispatch_targets(data)
    pending.extend(text_targets)
    targets.update(text_targets)
    # These addresses are entry points identified by the supplied laser notes.
    # Keep them separate from automatically discovered direct control flow.
    pending.extend([0xECD4, 0xEE10])
    runtime_seed_path = ROOT / 'src' / 'runtime-code-seeds.json'
    runtime_seeds = []
    if runtime_seed_path.exists():
        runtime_evidence = json.loads(runtime_seed_path.read_text())
        if runtime_evidence.get('reference_sha256') != REFERENCE_SHA256:
            raise ValueError('Runtime code seeds belong to a different reference TAP')
        if runtime_evidence.get('machine') != 'ZX Spectrum 48K':
            raise ValueError('Runtime code seeds were not captured in ZX Spectrum 48K mode')
        runtime_seeds = [int(value, 16) for value in runtime_evidence['instruction_addresses']]
        pending.extend(runtime_seeds)
    while pending:
        pc = pending.popleft()
        if not BASE <= pc < end or pc in code:
            continue
        if any(r['start'] <= pc < r['end'] for r in known_data):
            raise ValueError(f'Control flow enters verified graphics data at ${pc:04X}')
        if pc in owners:
            conflicts.append(pc)
            continue
        ins = decoder.disassemble(pc, pc+1, 'h')[0]
        op, size = ins.operation, len(ins.data)
        if op.startswith('DEFB') or pc + size > end:
            continue
        if any(a in owners for a in range(pc, pc+size)):
            conflicts.append(pc)
            continue
        code[pc] = ins
        for a in range(pc, pc+size): owners[a] = pc
        m = re.match(r'^(?:JP|JR|CALL|DJNZ) (?:[A-Z]+,)?\$([0-9A-F]{4})$', op)
        if m:
            target = int(m[1],16)
            if BASE <= target < end:
                targets.add(target); pending.append(target)
        # Stop at unconditional jumps/returns and indirect dispatches.
        terminal = op in ('RET','RETI','RETN') or re.match(r'^(JP|JR) (\$|\()',op)
        # ROM calculator uses inline bytecode. Do not misclassify it as Z80.
        if op == 'RST $28': terminal = True
        if not terminal:
            pending.append(pc+size)

    # All absolute 16-bit references into the image get neutral labels. Values
    # loaded into register pairs may be pointers or literal constants; these
    # inferred references are listed in the report and need semantic review.
    refs = set(targets)
    inferred = []
    for pc, ins in code.items():
        for m in re.finditer(r'\$([0-9A-F]{4})\b', ins.operation):
            value = int(m[1],16)
            if BASE <= value < end:
                refs.add(value)
                if ins.operation.startswith(('LD BC,','LD DE,','LD HL,','LD IX,','LD IY,','LD SP,')):
                    inferred.append(dict(address=pc, value=value, operation=ins.operation))
    # Force landmarks to exist even when they are data/operands, never fake code.
    notes = {
        BASE+0x23: ('StationBlueprintPointer', 'VERIFIED: persistent slot-zero station blueprint pointer; must follow model relocation.'),
        0x7000: ('Entry', 'VERIFIED: BASIC RANDOMIZE USR 28672 enters here.'),
        0x716B: ('Startup', 'Direct target of the entry JP at $7000.'),
        0x7181: ('StartupAfterGraphicsCopy', 'VERIFIED: font and cockpit colours have been relocated before their source RAM is reused.'),
        0x7398: ('BlitViewBitmap', 'VERIFIED: reads the reused $C000/$C800 view buffers, not the initial on-tape font/cockpit data.'),
        0x743B: ('RestoreCockpitBitmap', 'VERIFIED: restore 256x64 bitmap from CockpitBitmap to the bottom screen third.'),
        0x7446: ('RestoreCockpitAttributes', 'VERIFIED: restore 32x8 colour cells from the runtime attribute buffer.'),
        0x7451: ('CockpitRestored', 'Bitmap and attribute copies are complete; instrument updates follow.'),
        0x8F47: ('SaveCockpitBitmap', 'VERIFIED: save the current cockpit bitmap into the reused CockpitBitmap buffer.'),
        0x8F52: ('SaveCockpitAttributes', 'VERIFIED: save the current cockpit colours into the runtime attribute buffer.'),
        0x8F5D: ('CockpitSaved', 'Bitmap and attribute backup copies are complete.'),
        0xBB69: ('GetCharacterBitmap', 'VERIFIED: FontRuntime + (A-FontFirstCode)*8 selects a relocated glyph.'),
        0xBBBD: ('DrawCharacterRow', 'VERIFIED: XOR one font byte into a screen row, then advance glyph and screen pointers.'),
        0xBBC5: ('CharacterDrawn', 'Eight character rows have been drawn.'),
        55237: ('MissionGalaxyGateOperand', 'POKE reference: allow missions/pirates in galaxy 1; original byte $4E. Meaning needs surrounding-code review.'),
        55298: ('PirateEscapePatchSite', 'POKE reference: 3-byte pirate escape patch site; keep original bytes.'),
        55310: ('PirateChanceOperand', 'POKE reference: forcing boarding changes this original $05 byte to $00.'),
        55315: ('PirateBoardingCompare', 'POKE reference: disable boarding by changing the original $BE byte to $FE.'),
        43047: ('CurrentGalaxy', 'Research note: current galaxy, zero-based; corroborate all reads before changing format.'),
        0xECD4: ('DrawLaser', 'VERIFIED: draw player laser beams with the original random endpoint wiggle.'),
        0xECF2: ('LaserPatchSite', 'Optional single-beam dispatch; default keeps the original multiple line calls.'),
        0xECFE: ('LaserOriginalContinuation', 'Original first-beam continuation; unreachable with laser=single.'),
        0xEE10: ('DrawLine', 'VERIFIED: shared clipped line renderer. HL/DE are endpoint magnitudes; C holds quadrant bits.'),
        64749: ('UnusedAfterReturnCandidate', 'Research note: proposed pirate patch storage before interrupt-vector region. Preserved, not used.'),
        65384: ('KeySwapMaskB1', 'POKE reference: first B/Symbol Shift mask pair.'),
        65385: ('KeySwapMaskB2', 'POKE reference: first B/Symbol Shift mask pair.'),
        65432: ('KeySwapMaskShift1', 'POKE reference: second B/Symbol Shift mask pair.'),
        65433: ('KeySwapMaskShift2', 'POKE reference: second B/Symbol Shift mask pair.'),
    }
    for region in known_data:
        notes[region['start']] = (region['name'],region['comment'])
    for address, (name, comments) in ANNOTATIONS.items():
        if address in notes:
            raise ValueError(f'Duplicate annotation at ${address:04X}')
        notes[address] = (name, 'VERIFIED: '+comments[0])
    refs.update(notes)
    # Boundaries for optional initial data and startup code in original zero fill.
    refs.update([0xC600, 0xC640, 0x7189, 0xA777])
    labels = {a: notes[a][0] if a in notes else f'L_{a:04X}' for a in refs}
    # A reference into an instruction names its byte position relative to that
    # instruction, so operand labels survive earlier relocation automatically.
    interior = {a:owners[a] for a in refs if a in owners and owners[a] != a}
    for start in interior.values(): labels.setdefault(start,f'L_{start:04X}')
    for region in known_data:
        if any(a in owners for a in range(region['start'],region['end'])):
            raise ValueError('Instruction overlaps known data: '+region['name'])
        if region in graphics_data:
            emit_graphics(region,memory,labels,data)
            if region['name'] == 'FontBitmap':
                font, patch_payload = patch_font()
                if len(font) != region['end']-region['start']:
                    raise ValueError('PATCH128 font size differs from the reference font')
                patch_memory = memory.copy()
                patch_memory[region['start']:region['end']] = font
                emit_graphics(dict(region, file='font-48.asm'), patch_memory, labels,
                              patch_payload, prologue(5, patch_payload, PATCH_SOURCE, PATCH_SHA256))
                patch_memory[region['start']:region['end']] = fixed_font(bytes(memory[region['start']:region['end']]))
                provenance = ['; Fixes the corrupted Status Indicator in the Elite 128K instrument panel.',
                              '; Hybrid font: original font.asm with codes $21..$26 from font-48.asm.',
                              '; Both sources: TAP data block 5, load $6048; font source $C000.',
                              '; PATCH128.TAP SHA256: '+PATCH_SHA256] + prologue(5, data)
                emit_graphics(dict(region, file='font-128fix.asm'), patch_memory, labels, data, provenance)
                patch_memory[region['start']:region['end']] = fixed_font(bytes(memory[region['start']:region['end']]), ecm_s=True)
                provenance = ['; Fixes the corrupted Status Indicator in the Elite 128K instrument panel and uses the smaller ECM and S indicators from the 48K version.', '; Hybrid font: original font.asm with codes $21..$26, $3B..$3E and $5B..$5E from font-48.asm.', '; Both sources: TAP data block 5, load $6048; font source $C000.', '; PATCH128.TAP SHA256: fac185ce4248e1dccc99f93a7cb7d2791e220543c24016a3a77a1dfff4cbec47'] + prologue(5, data)
                emit_graphics(dict(region, file='font-128fix_ecm_s.asm'), patch_memory, labels, data, provenance)
        elif region['name'] == 'ShipBlueprintsAndDispatchTables':
            _, blueprint_image, blueprint_records = analyze_ship_blueprints()
            if blueprint_image != data:
                raise ValueError('Ship analysis and source reconstruction use different game images')
            write(SOURCE / 'data' / region['file'], render_ship_blueprints(data, blueprint_records))
            write_variant_sources(data)
        else:
            emit_verified_data(region,memory,labels,data)
    # Decode each verified copy/lookup operand symbolically, including its length.
    # Fail loudly if the original instruction ever ceases to match this analysis.
    overrides = {
        0x716E: ('LD DE,$5D70','LD DE,FontRuntime'),
        0x7171: ('LD BC,$02D8','LD BC,FontBitmapSize'),
        0x7179: ('LD DE,$5B00','LD DE,CockpitAttributesRuntime'),
        0x717C: ('LD BC,$0100','LD BC,CockpitAttributesSize'),
        0x739B: ('LD HL,$C000','LD HL,ViewBitmapBuffer'),
        0x73A4: ('LD HL,$C800','LD HL,ViewBitmapBufferSecondHalf'),
        0x743B: ('LD DE,$5000','LD DE,ScreenCockpitBitmap'),
        0x7441: ('LD BC,$0800','LD BC,CockpitBitmapSize'),
        0x7446: ('LD DE,$5A00','LD DE,ScreenCockpitAttributes'),
        0x7449: ('LD HL,$5B00','LD HL,CockpitAttributesRuntime'),
        0x744C: ('LD BC,$0100','LD BC,CockpitAttributesSize'),
        0x8F4A: ('LD HL,$5000','LD HL,ScreenCockpitBitmap'),
        0x8F4D: ('LD BC,$0800','LD BC,CockpitBitmapSize'),
        0x8F52: ('LD DE,$5B00','LD DE,CockpitAttributesRuntime'),
        0x8F55: ('LD HL,$5A00','LD HL,ScreenCockpitAttributes'),
        0x8F58: ('LD BC,$0100','LD BC,CockpitAttributesSize'),
        0xBB69: ('LD HL,$5D70','LD HL,FontRuntime'),
        0xBB6C: ('SUB $20','SUB FontFirstCode'),
        0xBBBB: ('LD B,$08','LD B,FontGlyphHeight'),
        # B/C are numeric parameters here, not a pointer into ship geometry.
        0xD55E: ('LD BC,$640A','LD BC,$640A'),
    }
    for pc,(expected,_) in overrides.items():
        if pc not in code or code[pc].operation != expected:
            raise ValueError(f'Annotated graphics instruction changed at ${pc:04X}')
    lines = prologue(5, data) + [
        '; Control-flow reconstruction from entry $7000 and supplied laser entry hints.',
        '; Identified runtime state, models, text, commander, math and graphics data are isolated in data/*.asm.',
        '; Remaining DEFB bytes are UNCLASSIFIED.',
        '; Every original byte is present. This is not yet a fully documented disassembly.',
    ]
    lines += ['; Fixed runtime/screen destinations and character format, verified from original instructions.']
    lines += ['    INCLUDE "options.asm"']
    # Fixed runtime workspaces come from the reference memory map; movable
    # on-tape font/graphics sources use their emitted labels instead.
    lines += [f'defc {name} = ${value:04X}' for name,value in graphics_constants.items()]
    lines += ['; Source RAM is reused after the initial font/colour copies.',
              'defc ViewBitmapBuffer = FontBitmap',
              'defc ViewBitmapBufferSecondHalf = CockpitBitmap',
              'org GameLoadAddress', 'GameImage:']
    pc = BASE
    ranges=[]
    while pc < end:
        region=next((r for r in known_data if r['start']==pc),None)
        if region:
            lines += ['', '; KNOWN DATA: '+region['comment']]
            if region['name'] == 'FontBitmap':
                lines += ['IF FONT_48', '    INCLUDE "data/font-48.asm"', 'ELSE', 'IF FONT_128FIX', '    INCLUDE "data/font-128fix.asm"', 'ELSE', 'IF FONT_128FIX_ECM_S', '    INCLUDE "data/font-128fix_ecm_s.asm"', 'ELSE']
            lines += ['    INCLUDE "data/'+region['file']+'"']
            if region['name'] == 'FontBitmap':
                lines += ['ENDIF', 'ENDIF', 'ENDIF']
            lines += ['']
            ranges.append(dict(start=pc,end=region['end'],kind='data',name=region['name']))
            pc=region['end']
            continue
        if pc == 0xECFE:
            lines.append('ENDIF')
        if pc == 0x7189:
            lines.append('ENDIF')
        if pc == 0xA706:
            lines += ['ENDIF', 'assert $-GameImage = CockpitIndicatorsLimit-$6048']
        if pc == 0xF470:
            lines.append('ENDIF')
        if pc in notes:
            lines += ['', '; ' + notes[pc][1]]
            if pc in ANNOTATIONS:
                lines += ['; '+line for line in ANNOTATIONS[pc][1][1:]]
        if pc == 0x716B:
            lines += ['IF SHIP_ADDER', 'Startup:',
                      '    INCLUDE "data/text-dispatch-first.asm"',
                      '    defs 2,0 ; preserve the original reclaimed-slot padding',
                      'defc StartupAfterGraphicsCopy = AdderStartupAfterGraphicsCopy',
                      'ELSE']
        if pc in labels and pc not in interior:
            lines += [labels[pc]+':']
            if pc in ANNOTATIONS:
                lines += [f'L_{pc:04X}: ; legacy analysis alias; same address, no emitted bytes']
        if pc == 0xA660:
            lines += ['IF SCANNER_PIXEL_FIX', '    INCLUDE "scanner-pixel-fix.asm"', 'ELSE']
        if pc == 0xF44A:
            lines += ['IF STATION_RANDOM_LAUNCH_FIX', '    INCLUDE "station-random-launch-fix.asm"', 'ELSE']
        if pc == 0xF470:
            lines += ['    assert SelectParentLaunchType-GameImage = ParentLaunchSelectionStart-$6048',
                      '    assert LaunchSelectedShip-GameImage = ParentLaunchSelectionLimit-$6048']
        if pc == 0xD0F8:
            # The preceding L_BA99 consumes only the space. Execution resumes
            # at LD B,$12, not at the linear decoder's JR NZ / LD (DE),A.
            if bytes(memory[pc:pc+3]) != bytes.fromhex('20 06 12'):
                raise ValueError('Legal-status inline space/token setup changed')
            lines += ['    defb $20                                   ; Space character; L_BA99 prints it and advances its return address past this byte.',
                      '    LD B,$12                                   ; $D0F9: 06 12; Clean text-token index']
            ranges += [dict(start=pc,end=pc+1,kind='data',name='LegalStatusSeparator'),
                       dict(start=pc+1,end=pc+3,kind='code')]
            pc += 3
            continue
        if pc == 0xD137:
            # L_BA99 consumes one inline character, then returns to the CALL.
            # Linear decoding mistakes the four bytes for LD DE,nn / POP DE.
            if bytes(memory[pc:pc+4]) != bytes.fromhex('11 CD A6 D1'):
                raise ValueError('Status-screen inline character/CALL changed')
            lines += ['    defb $11                                   ; Inline character consumed by L_BA99',
                      '    CALL L_D1A6                                ; $D138: CD A6 D1']
            pc += 4
            continue
        if pc == 0xECF2:
            lines += ['IF LASER_SINGLE', '    INCLUDE "single-laser.asm"',
                      '    defw DrawLine ; unreachable original CALL operand bytes; preserve the layout',
                      'ELSE']
        if pc == 0xECFE:
            lines += ['IF LASER_SINGLE',
                      '    assert SingleLaserEnd+2 = LaserOriginalContinuation', 'ENDIF']
        if pc == 0xC600:
            if any(memory[pc:0xC640]):
                raise ValueError('Optional startup storage is no longer zero-filled')
            lines += ['IF SHIP_ADDER', '    INCLUDE "adder-startup.asm"', 'ENDIF',
                      '    defs (VariantStartupLimit-GameLoadAddress)-($-GameImage),0']
            ranges.append(dict(start=pc,end=0xC640,kind='data',name='OptionalAdderStartup'))
            pc = 0xC640
            continue
        for a,start in sorted(interior.items()):
            if start == pc:
                if a in notes: lines += ['; ' + notes[a][1]]
                lines += [f'defc {labels[a]} = {labels[start]} + {a-start} ; byte inside instruction at ${start:04X}']
        if pc in code:
            ins = code[pc]
            op = re.sub(r'\$([0-9A-F]{4})\b', lambda m: labels.get(int(m[1],16),m[0]), ins.operation)
            if pc in overrides: op=overrides[pc][1]
            if pc == ENTRY:
                lines += ['IF SHIP_ADDER', '    JP AdderStartup', 'ELSE']
            if pc in (0xF302,0xF308):
                lines += ['IF SHIP_ADDER', '    NOP ; compact two-byte blueprint pointers', 'ELSE']
            lines += [f'    {op:<42} ; ${pc:04X}: ' + bytes(ins.data).hex(' ').upper()]
            if pc in (ENTRY,0xF302,0xF308):
                lines.append('ENDIF')
            size=len(ins.data); kind='code'
        else:
            size=1
            while size<16 and pc+size<end and pc+size not in code and pc+size not in labels:
                size+=1
            chunk=bytes(memory[pc:pc+size])
            text=''.join(chr(c) if 32 <= c < 127 else '.' for c in chunk)
            lines += [f'    {bytes_line(chunk):<85} ; ${pc:04X} {text}']
            kind='unclassified'
        if ranges and ranges[-1]['kind']==kind and ranges[-1]['end']==pc:
            ranges[-1]['end']+=size
        else:
            ranges.append(dict(start=pc,end=pc+size,kind=kind))
        pc+=size
    lines += ['', 'GameImageEnd:',f'assert GameImageEnd-GameImage = {len(data)}',
              f'assert Entry-GameImage = $7000-${BASE:04X}',
              f'assert GameImageEnd-GameImage = ${end:04X}-${BASE:04X}']
    lines += ['IF SHIP_ADDER',
              'assert AdderStartupEnd-AdderStartup <= CockpitAttributes-AdderStartup',
              'assert ContinueStartup-Startup = AdderStartupResumeJump-AdderStartup', 'ENDIF']
    for address,(name,_) in sorted(notes.items()):
        if name == 'StartupAfterGraphicsCopy':
            lines.append('IF !SHIP_ADDER')
        if name == 'DrawMissileIndicators':
            lines.append('IF !SCANNER_PIXEL_FIX')
        if address in interior:
            start = interior[address]
            lines += [f'assert ({labels[start]}-GameImage)+{address-start} = ${address:04X}-${BASE:04X}']
        else:
            lines += [f'assert {name}-GameImage = ${address:04X}-${BASE:04X}']
        if name == 'StartupAfterGraphicsCopy':
            lines.append('ENDIF')
        if name == 'DrawMissileIndicators':
            lines.append('ENDIF')
    for region in known_data:
        lines += [f'assert {region["name"]}End-GameImage = ${region["end"]:04X}-${BASE:04X}']
    lines += ['']
    write(SOURCE/'game.asm','\n'.join(lines))
    return dict(image_start=BASE,image_end_exclusive=end,entry=ENTRY,
                code_instructions=len(code),code_bytes=len(owners),
                known_data_bytes=sum(r['end']-r['start'] for r in known_data),
                unclassified_bytes=sum(r['end']-r['start'] for r in ranges if r['kind']=='unclassified'),
                known_data=[dict(name=r['name'],file=r['file'],start=r['start'],end=r['end'],comment=r['comment'])
                            for r in known_data],
                graphics_data=[dict(name=r['name'],file=r['file'],start=r['start'],end=r['end'],comment=r['comment'])
                               for r in graphics_data],
                graphics_constants=graphics_constants,
                runtime_code_seeds=len(runtime_seeds),
                overlap_conflicts=sorted(set(conflicts)),inferred_pointer_immediates=inferred,ranges=ranges,
                landmarks=[dict(address=a,label=n,reference_byte=memory[a],comment=c) for a,(n,c) in sorted(notes.items())])

def main():
    p=argparse.ArgumentParser();p.add_argument('--force',action='store_true');args=p.parse_args()
    if any(SOURCE.rglob('*.asm')) and not args.force:
        raise SystemExit('Source already exists; refusing to overwrite annotations. Use --force only deliberately.')
    data,blocks=reference()
    basic(blocks[1].payload);screen(blocks[3].payload);report=image(blocks[5].payload)
    report.update(reference_sha256=sha(data),tape_blocks=describe(blocks))
    dest=ROOT/'docs/generated/reconstruction.json';dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8',newline='\n')
    print(f"Source generated: {report['code_instructions']} code candidates / {report['code_bytes']} bytes; {report['known_data_bytes']} known data bytes; {report['unclassified_bytes']} unclassified bytes.")

if __name__=='__main__': main()
