; Reconstructed from assets/Elite - 128k.tap; no original binary is included at build time.
; TAP SHA256: d9013872555f448308e0b8a69b624600335384cd38911165bde74a9d11de84d6
; Zero-based TAP data block 1; payload SHA256: d756436cffdd705c707a93024ac393e0e8147363aa552290899e310e96bdcb67
; Generated by tools/bootstrap_sources.py. Normal builds assemble this file directly.

org 0
BasicProgram:

; 5 SAVE "ELITE" LINE 10: VERIFY "": STOP
BasicLine_5:
    defb 5 >> 8,5 & $FF
    defw BasicLine_5_End - BasicLine_5_Body
BasicLine_5_Body:
    defb $F8,$22,$45,$4C,$49,$54,$45,$22,$CA,$31,$30,$0E,$00,$00,$0A,$00
    defb $00,$3A,$D6,$22,$22,$3A,$E2,$0D
BasicLine_5_End:

; 10 CLEAR 65535
BasicLine_10:
    defb 10 >> 8,10 & $FF
    defw BasicLine_10_End - BasicLine_10_Body
BasicLine_10_Body:
    defb $FD,$36,$35,$35,$33,$35,$0E,$00,$00,$FF,$FF,$00,$0D
BasicLine_10_End:

; 15 BORDER 0: PAPER 0: INK 0: CLS
BasicLine_15:
    defb 15 >> 8,15 & $FF
    defw BasicLine_15_End - BasicLine_15_Body
BasicLine_15_Body:
    defb $E7,$30,$0E,$00,$00,$00,$00,$00,$3A,$DA,$30,$0E,$00,$00,$00,$00
    defb $00,$3A,$D9,$30,$0E,$00,$00,$00,$00,$00,$3A,$FB,$0D
BasicLine_15_End:

; 20 LOAD "" SCREEN$: PRINT AT 20,0;: LOAD "" CODE
BasicLine_20:
    defb 20 >> 8,20 & $FF
    defw BasicLine_20_End - BasicLine_20_Body
BasicLine_20_Body:
    defb $EF,$22,$22,$AA,$3A,$F5,$AC,$32,$30,$0E,$00,$00,$14,$00,$00,$2C
    defb $30,$0E,$00,$00,$00,$00,$00,$3B,$3A,$EF,$22,$22,$AF,$0D
BasicLine_20_End:

; 30 RANDOMIZE USR 28672 ($7000)
BasicLine_30:
    defb 30 >> 8,30 & $FF
    defw BasicLine_30_End - BasicLine_30_Body
BasicLine_30_Body:
    defb $F9,$C0,$32,$38,$36,$37,$32,$0E,$00,$00,$00,$70,$00,$0D
BasicLine_30_End:

BasicProgramEnd:
assert BasicProgramEnd-BasicProgram = 130
