; Reconstructed from assets/Elite - 128k.tap; no original binary is included at build time.
; TAP SHA256: d9013872555f448308e0b8a69b624600335384cd38911165bde74a9d11de84d6
; Zero-based TAP data block 5; payload SHA256: 55de3c7f56b1d54434c6b1a7b360174a1f56252e839abdce5463526128e1ff07
; Generated by tools/bootstrap_sources.py. Normal builds assemble this file directly.

; KNOWN DATA: $A816..$A87D, 104 bytes.
; VERIFIED DATA: mutable 104-byte commander buffer used directly by ROM tape load/save; the first 102 bytes follow the supplied save map.
; Field-level names remain for later analysis where the exact format is not yet proved.

ActiveCommanderRecord:
    defb $4A,$41,$4D,$45,$53,$4F,$4E,$20,$20,$20,$00                                      ; $A816 JAMESON   .

; VERIFIED: Unsigned legal score in ActiveCommanderRecord at offset 11.
; Status display: 0 Clean, 1..49 Offender, 50..255 Fugitive.
; Viper and Fer-de-Lance AI becomes hostile at 40, before the Fugitive boundary.
; Evidence: SelectLegalStatusToken, UpdateShipHostilityAndSteering and tools/check_bounty_hunters.py.
PlayerLegalScore:
L_A821: ; legacy analysis alias; same address, no emitted bytes
    defb $00                                                                              ; $A821 .
L_A822:
    defb $00                                                                              ; $A822 .
L_A823:
    defb $00                                                                              ; $A823 .
L_A824:
    defb $00                                                                              ; $A824 .
L_A825:
    defb $00,$00                                                                          ; $A825 ..
CurrentGalaxy:
    defb $01                                                                              ; $A827 .
L_A828:
    defb $00                                                                              ; $A828 .
L_A829:
    defb $00                                                                              ; $A829 .
L_A82A:
    defb $00,$00                                                                          ; $A82A ..
L_A82C:
    defb $00                                                                              ; $A82C .
L_A82D:
    defb $00,$00,$00                                                                      ; $A82D ...
L_A830:
    defb $00,$00,$00                                                                      ; $A830 ...
L_A833:
    defb $00,$00,$00,$00                                                                  ; $A833 ....
L_A837:
    defb $00,$00,$00,$00,$00                                                              ; $A837 .....
L_A83C:
    defb $00,$00                                                                          ; $A83C ..
L_A83E:
    defb $00                                                                              ; $A83E .
L_A83F:
    defb $00,$00,$00,$00                                                                  ; $A83F ....
L_A843:
    defb $00                                                                              ; $A843 .
L_A844:
    defb $00                                                                              ; $A844 .
L_A845:
    defb $00                                                                              ; $A845 .
L_A846:
    defb $00                                                                              ; $A846 .
L_A847:
    defb $00,$00,$00                                                                      ; $A847 ...
L_A84A:
    defb $00                                                                              ; $A84A .
L_A84B:
    defb $00                                                                              ; $A84B .
L_A84C:
    defb $00                                                                              ; $A84C .
L_A84D:
    defb $00                                                                              ; $A84D .
L_A84E:
    defb $00                                                                              ; $A84E .
L_A84F:
    defb $00,$00,$00                                                                      ; $A84F ...
L_A852:
    defb $00,$00,$00,$00,$00,$00                                                          ; $A852 ......
L_A858:
    defb $00                                                                              ; $A858 .
L_A859:
    defb $00,$00                                                                          ; $A859 ..
L_A85B:
    defb $00,$00,$00                                                                      ; $A85B ...
L_A85E:
    defb $00                                                                              ; $A85E .
L_A85F:
    defb $00                                                                              ; $A85F .
L_A860:
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00                  ; $A860 ................
L_A870:
    defb $00                                                                              ; $A870 .
L_A871:
    defb $00                                                                              ; $A871 .
L_A872:
    defb $00                                                                              ; $A872 .
L_A873:
    defb $27,$08,$00,$00,$0A,$19,$00,$00,$3D                                              ; $A873 '.......=
L_A87C:
    defb $00                                                                              ; $A87C .
L_A87D:
    defb $00                                                                              ; $A87D .

ActiveCommanderRecordEnd:
defc ActiveCommanderRecordSize = ActiveCommanderRecordEnd - ActiveCommanderRecord
assert ActiveCommanderRecordSize = 104
