; Reconstructed from assets/Elite - 128k.tap; no original binary is included at build time.
; TAP SHA256: d9013872555f448308e0b8a69b624600335384cd38911165bde74a9d11de84d6
; Zero-based TAP data block 5; payload SHA256: 55de3c7f56b1d54434c6b1a7b360174a1f56252e839abdce5463526128e1ff07
; Generated by tools/bootstrap_sources.py. Normal builds assemble this file directly.

; KNOWN DATA: $C700..$C7FF, 256 bytes.
; VERIFIED initial cockpit colours: 32 columns x 8 character rows. Copied to CockpitAttributesRuntime at startup.
; The on-tape data is initial content, NOT read-only runtime storage.
; The $C000..$CFFF area is later reused by graphics buffers and temporary stack.
; Each byte: FLASH bit 7, BRIGHT bit 6, PAPER bits 5..3, INK bits 2..0.
; Rows map to character rows 16..23 of the display.

; Character row 16.
CockpitAttributes:
    defb $07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07 ; $C700
    defb $07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07 ; $C710

; Character row 17.
    defb $07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07,$07,$07,$07,$07,$07 ; $C720
    defb $07,$07,$07,$07,$07,$07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07 ; $C730

; Character row 18.
    defb $07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07,$07,$07,$07,$07,$07 ; $C740
    defb $07,$07,$07,$07,$07,$07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07 ; $C750

; Character row 19.
    defb $07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07,$07,$07,$07,$07,$07 ; $C760
    defb $07,$07,$07,$07,$07,$07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07 ; $C770

; Character row 20.
    defb $07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07,$07,$07,$07,$07,$07 ; $C780
    defb $07,$07,$07,$07,$07,$07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07 ; $C790

; Character row 21.
    defb $07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07,$07,$07,$07,$07,$07 ; $C7A0
    defb $07,$07,$07,$07,$07,$07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07 ; $C7B0

; Character row 22.
    defb $07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07,$07,$07,$07,$07,$07 ; $C7C0
    defb $07,$07,$07,$07,$07,$07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07 ; $C7D0

; Character row 23.
    defb $07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07,$07,$07,$07,$07,$07 ; $C7E0
    defb $07,$07,$07,$07,$07,$07,$07,$07,$17,$17,$17,$17,$17,$07,$07,$07 ; $C7F0

CockpitAttributesEnd:
defc CockpitAttributesSize = CockpitAttributesEnd - CockpitAttributes
assert CockpitAttributesEnd-CockpitAttributes = 256
