; Reconstructed from assets/Elite - 128k.tap; no original binary is included at build time.
; TAP SHA256: d9013872555f448308e0b8a69b624600335384cd38911165bde74a9d11de84d6
; Zero-based TAP data block 5; payload SHA256: 55de3c7f56b1d54434c6b1a7b360174a1f56252e839abdce5463526128e1ff07
; Generated by tools/bootstrap_sources.py. Normal builds assemble this file directly.

; KNOWN DATA: $C800..$CFFF, 2048 bytes.
; VERIFIED initial cockpit bitmap: 256 x 64 pixels in Spectrum screen order. Copied to ScreenCockpitBitmap.
; The on-tape data is initial content, NOT read-only runtime storage.
; The $C000..$CFFF area is later reused by graphics buffers and temporary stack.
; Source offset = ((y & 7) << 8) | ((y & $38) << 2) | (x >> 3).
; Local y=0..63 maps to physical screen y=128..191.
; This address also holds saved panel state or the second view-buffer half.

; Physical screen pixel row 128.
CockpitBitmap:
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $C800
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $C810

; Physical screen pixel row 136.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$00,$00,$00,$00,$00,$00,$00,$00 ; $C820
    defb $00,$00,$00,$00,$00,$00,$00,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $C830

; Physical screen pixel row 144.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$7F,$FE,$00,$00,$00,$00,$00,$00 ; $C840
    defb $00,$00,$00,$00,$00,$20,$00,$05,$00,$00,$00,$00,$01,$00,$01,$00 ; $C850

; Physical screen pixel row 152.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$00,$00,$08,$00,$08,$02,$00,$00 ; $C860
    defb $00,$40,$10,$00,$10,$08,$00,$11,$00,$00,$00,$00,$01,$00,$01,$00 ; $C870

; Physical screen pixel row 160.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$00,$80,$00,$08,$00,$00,$02,$00 ; $C880
    defb $40,$00,$00,$10,$00,$01,$00,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $C890

; Physical screen pixel row 168.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$01,$00,$08,$00,$00,$00,$00,$00 ; $C8A0
    defb $00,$00,$00,$00,$10,$00,$80,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $C8B0

; Physical screen pixel row 176.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$00,$01,$80,$00,$00,$00,$00,$00 ; $C8C0
    defb $00,$00,$00,$00,$01,$80,$00,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $C8D0

; Physical screen pixel row 184.
    defb $00,$80,$01,$00,$00,$00,$00,$81,$00,$00,$00,$00,$0F,$80,$00,$00 ; $C8E0
    defb $00,$01,$F0,$00,$00,$00,$00,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $C8F0

; Physical screen pixel row 129.
L_C900:
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $C900
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $C910

; Physical screen pixel row 137.
    defb $00,$BF,$3D,$FF,$FF,$FF,$FE,$01,$03,$C0,$00,$00,$00,$00,$00,$00 ; $C920
    defb $00,$00,$00,$00,$00,$00,$7E,$01,$00,$00,$00,$00,$01,$3E,$FD,$00 ; $C930

; Physical screen pixel row 145.
    defb $00,$BC,$3D,$FF,$FC,$00,$00,$01,$7F,$FE,$00,$00,$00,$00,$55,$55 ; $C940
    defb $55,$00,$00,$00,$00,$20,$00,$05,$00,$00,$18,$00,$01,$7E,$81,$00 ; $C950

; Physical screen pixel row 153.
    defb $00,$BF,$45,$FF,$FF,$FF,$FF,$FD,$00,$00,$20,$00,$00,$01,$00,$00 ; $C960
    defb $00,$80,$00,$00,$04,$04,$00,$21,$00,$18,$00,$00,$01,$78,$FD,$00 ; $C970

; Physical screen pixel row 161.
    defb $00,$BF,$7D,$E0,$00,$00,$00,$01,$00,$00,$00,$00,$00,$00,$01,$00 ; $C980
    defb $80,$00,$00,$00,$00,$00,$00,$01,$FF,$FF,$FF,$FF,$C1,$03,$81,$00 ; $C990

; Physical screen pixel row 169.
    defb $00,$A0,$7D,$00,$00,$00,$00,$01,$01,$00,$00,$00,$00,$00,$00,$08 ; $C9A0
    defb $00,$00,$00,$00,$00,$00,$80,$01,$FF,$FF,$FF,$FF,$FF,$07,$E1,$00 ; $C9B0

; Physical screen pixel row 177.
    defb $00,$BC,$41,$FF,$FF,$FF,$FF,$FD,$00,$00,$60,$00,$00,$00,$00,$08 ; $C9C0
    defb $00,$00,$00,$00,$06,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$07,$E1,$00 ; $C9D0

; Physical screen pixel row 185.
    defb $00,$B0,$01,$00,$00,$00,$00,$81,$00,$00,$00,$00,$00,$7F,$80,$08 ; $C9E0
    defb $01,$FE,$00,$00,$00,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$06,$01,$00 ; $C9F0

; Physical screen pixel row 130.
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CA00
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CA10

; Physical screen pixel row 138.
    defb $00,$A0,$41,$FF,$FF,$FF,$FE,$01,$0F,$F0,$00,$00,$00,$00,$00,$00 ; $CA20
    defb $00,$00,$00,$00,$00,$01,$81,$81,$00,$00,$00,$00,$01,$40,$85,$00 ; $CA30

; Physical screen pixel row 146.
    defb $00,$A2,$41,$FF,$FC,$00,$00,$01,$7F,$FE,$00,$00,$00,$15,$00,$00 ; $CA40
    defb $00,$54,$00,$00,$00,$20,$00,$05,$00,$00,$18,$00,$01,$42,$81,$00 ; $CA50

; Physical screen pixel row 154.
    defb $00,$A0,$45,$FF,$FF,$FF,$FF,$FD,$00,$00,$80,$00,$20,$00,$80,$00 ; $CA60
    defb $01,$00,$04,$00,$01,$02,$00,$41,$00,$18,$00,$00,$01,$44,$81,$00 ; $CA70

; Physical screen pixel row 162.
    defb $00,$A0,$11,$E0,$00,$00,$00,$01,$01,$00,$00,$20,$00,$00,$00,$81 ; $CA80
    defb $00,$00,$00,$04,$00,$00,$80,$01,$FF,$FF,$FF,$FF,$C1,$01,$81,$00 ; $CA90

; Physical screen pixel row 170.
    defb $00,$A0,$11,$00,$00,$00,$00,$01,$00,$80,$20,$00,$00,$00,$00,$00 ; $CAA0
    defb $00,$00,$00,$00,$04,$01,$00,$01,$FF,$FF,$FF,$FF,$FF,$00,$61,$00 ; $CAB0

; Physical screen pixel row 178.
    defb $00,$A2,$41,$FF,$FF,$FF,$FF,$FD,$00,$00,$18,$00,$00,$00,$00,$00 ; $CAC0
    defb $00,$00,$00,$00,$18,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$00,$61,$00 ; $CAD0

; Physical screen pixel row 186.
    defb $00,$AF,$F9,$00,$00,$00,$00,$81,$00,$00,$00,$00,$00,$00,$7F,$FF ; $CAE0
    defb $FE,$00,$00,$00,$00,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$06,$61,$00 ; $CAF0

; Physical screen pixel row 131.
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CB00
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CB10

; Physical screen pixel row 139.
    defb $00,$BF,$39,$FF,$FF,$FF,$FE,$01,$1F,$F8,$00,$00,$00,$00,$00,$00 ; $CB20
    defb $00,$00,$00,$00,$00,$02,$00,$41,$00,$00,$00,$00,$01,$3C,$F9,$00 ; $CB30

; Physical screen pixel row 147.
    defb $00,$BE,$39,$FF,$FC,$00,$00,$01,$3F,$FC,$00,$00,$05,$C0,$00,$00 ; $CB40
    defb $00,$01,$A0,$00,$00,$20,$00,$05,$00,$00,$18,$00,$01,$7C,$81,$00 ; $CB50

; Physical screen pixel row 155.
    defb $00,$BF,$45,$FF,$FF,$FF,$FF,$FD,$00,$02,$22,$22,$04,$44,$40,$00 ; $CB60
    defb $02,$22,$20,$44,$44,$41,$81,$81,$00,$18,$00,$00,$01,$42,$81,$00 ; $CB70

; Physical screen pixel row 163.
    defb $00,$A0,$11,$E0,$00,$00,$00,$01,$02,$00,$00,$00,$00,$00,$00,$42 ; $CB80
    defb $00,$00,$00,$00,$00,$00,$40,$01,$FF,$FF,$FF,$FF,$C1,$01,$81,$00 ; $CB90

; Physical screen pixel row 171.
    defb $00,$A0,$11,$00,$00,$00,$00,$01,$00,$40,$00,$00,$00,$00,$00,$10 ; $CBA0
    defb $00,$00,$00,$00,$00,$02,$00,$01,$FF,$FF,$FF,$FF,$FF,$07,$E1,$00 ; $CBB0

; Physical screen pixel row 179.
    defb $00,$BE,$41,$FF,$FF,$FF,$FF,$FD,$00,$00,$06,$00,$00,$00,$00,$10 ; $CBC0
    defb $00,$00,$00,$00,$60,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$07,$E1,$00 ; $CBD0

; Physical screen pixel row 187.
    defb $00,$BF,$FD,$00,$00,$00,$00,$81,$00,$00,$00,$00,$00,$00,$00,$00 ; $CBE0
    defb $00,$00,$00,$00,$00,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$06,$61,$00 ; $CBF0

; Physical screen pixel row 132.
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CC00
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CC10

; Physical screen pixel row 140.
    defb $00,$A0,$05,$FF,$FF,$FF,$FE,$01,$3F,$FC,$00,$00,$00,$00,$00,$00 ; $CC20
    defb $00,$00,$00,$00,$00,$04,$00,$21,$00,$00,$00,$00,$01,$02,$81,$00 ; $CC30

; Physical screen pixel row 148.
    defb $00,$A2,$05,$FF,$FC,$00,$00,$01,$3F,$FC,$00,$00,$F0,$A0,$00,$00 ; $CC40
    defb $00,$05,$0F,$00,$00,$20,$00,$05,$00,$00,$18,$00,$01,$44,$81,$00 ; $CC50

; Physical screen pixel row 156.
    defb $00,$A0,$45,$FF,$FF,$FF,$FF,$FD,$00,$08,$00,$00,$80,$00,$20,$00 ; $CC60
    defb $04,$00,$01,$00,$00,$10,$7E,$01,$00,$18,$00,$00,$01,$42,$81,$00 ; $CC70

; Physical screen pixel row 164.
    defb $00,$A0,$11,$E0,$00,$00,$00,$01,$02,$00,$00,$80,$00,$00,$00,$24 ; $CC80
    defb $00,$00,$00,$01,$00,$00,$40,$01,$FF,$FF,$FF,$FF,$C1,$01,$81,$00 ; $CC90

; Physical screen pixel row 172.
    defb $00,$A0,$11,$00,$00,$00,$00,$01,$00,$20,$80,$00,$00,$00,$00,$00 ; $CCA0
    defb $00,$00,$00,$00,$01,$04,$00,$01,$FF,$FF,$FF,$FF,$FF,$06,$01,$00 ; $CCB0

; Physical screen pixel row 180.
    defb $00,$A2,$41,$FF,$FF,$FF,$FF,$FD,$00,$00,$01,$C0,$00,$00,$00,$00 ; $CCC0
    defb $00,$00,$00,$03,$80,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$00,$61,$00 ; $CCD0

; Physical screen pixel row 188.
    defb $00,$AF,$F9,$00,$00,$00,$00,$81,$00,$00,$00,$00,$00,$00,$00,$00 ; $CCE0
    defb $00,$00,$00,$00,$00,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$07,$E1,$00 ; $CCF0

; Physical screen pixel row 133.
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CD00
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CD10

; Physical screen pixel row 141.
    defb $00,$A0,$79,$FF,$FF,$FF,$FE,$01,$3F,$FC,$00,$00,$00,$00,$00,$00 ; $CD20
    defb $00,$00,$00,$00,$00,$08,$00,$11,$00,$00,$00,$00,$01,$7C,$81,$00 ; $CD30

; Physical screen pixel row 149.
    defb $00,$A2,$79,$FF,$FC,$00,$00,$01,$1F,$F8,$00,$0E,$00,$10,$00,$00 ; $CD40
    defb $00,$08,$00,$70,$00,$20,$00,$05,$00,$00,$18,$00,$01,$42,$FD,$00 ; $CD50

; Physical screen pixel row 157.
    defb $00,$A0,$7D,$FF,$FF,$FF,$FF,$FD,$00,$00,$00,$00,$00,$00,$10,$00 ; $CD60
    defb $08,$00,$00,$00,$00,$00,$00,$01,$00,$18,$00,$00,$01,$7E,$FD,$00 ; $CD70

; Physical screen pixel row 165.
    defb $00,$BF,$11,$E0,$00,$00,$00,$01,$03,$11,$10,$11,$11,$11,$11,$18 ; $CD80
    defb $88,$88,$88,$88,$11,$11,$40,$01,$FF,$FF,$FF,$FF,$C1,$07,$E1,$00 ; $CD90

; Physical screen pixel row 173.
    defb $00,$BE,$11,$00,$00,$00,$00,$01,$00,$10,$00,$00,$00,$00,$00,$08 ; $CDA0
    defb $00,$00,$00,$00,$00,$08,$00,$01,$FF,$FF,$FF,$FF,$FF,$07,$E1,$00 ; $CDB0

; Physical screen pixel row 181.
    defb $00,$A2,$7D,$FF,$FF,$FF,$FF,$FD,$00,$00,$00,$38,$00,$00,$00,$08 ; $CDC0
    defb $00,$00,$00,$1C,$00,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$07,$E1,$00 ; $CDD0

; Physical screen pixel row 189.
    defb $00,$B0,$01,$00,$00,$00,$00,$81,$00,$00,$00,$00,$00,$00,$00,$00 ; $CDE0
    defb $00,$00,$00,$00,$00,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$00,$61,$00 ; $CDF0

; Physical screen pixel row 134.
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CE00
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $CE10

; Physical screen pixel row 142.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$7F,$FE,$00,$00,$00,$00,$00,$00 ; $CE20
    defb $00,$00,$00,$00,$00,$10,$00,$09,$00,$00,$00,$00,$01,$00,$01,$00 ; $CE30

; Physical screen pixel row 150.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$0F,$F0,$00,$60,$02,$08,$00,$00 ; $CE40
    defb $00,$10,$40,$06,$00,$10,$00,$09,$00,$00,$00,$00,$01,$00,$01,$00 ; $CE50

; Physical screen pixel row 158.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$00,$20,$00,$02,$00,$00,$08,$00 ; $CE60
    defb $10,$00,$00,$40,$00,$04,$00,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $CE70

; Physical screen pixel row 166.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$02,$00,$02,$00,$00,$00,$00,$00 ; $CE80
    defb $00,$00,$00,$00,$40,$00,$40,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $CE90

; Physical screen pixel row 174.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$00,$0A,$00,$00,$00,$00,$00,$00 ; $CEA0
    defb $00,$00,$00,$00,$00,$50,$00,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $CEB0

; Physical screen pixel row 182.
    defb $00,$80,$01,$00,$00,$00,$00,$01,$00,$00,$00,$07,$00,$00,$00,$00 ; $CEC0
    defb $00,$00,$00,$E0,$00,$00,$00,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $CED0

; Physical screen pixel row 190.
    defb $00,$80,$01,$00,$00,$00,$00,$81,$00,$00,$00,$00,$00,$00,$00,$00 ; $CEE0
    defb $00,$00,$00,$00,$00,$00,$00,$01,$00,$00,$00,$00,$01,$00,$01,$00 ; $CEF0

; Physical screen pixel row 135.
    defb $00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; $CF00
    defb $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00 ; $CF10

; Physical screen pixel row 143.
    defb $00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$7F,$FE,$00,$00,$00,$00,$00,$00 ; $CF20
    defb $00,$00,$00,$00,$00,$10,$00,$09,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00 ; $CF30

; Physical screen pixel row 151.
    defb $00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$03,$C0,$03,$00,$00,$04,$00,$00 ; $CF40
    defb $00,$20,$00,$00,$C0,$10,$00,$09,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00 ; $CF50

; Physical screen pixel row 159.
    defb $00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$00,$00,$00,$00,$04,$00 ; $CF60
    defb $20,$00,$00,$00,$00,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00 ; $CF70

; Physical screen pixel row 167.
    defb $00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$02,$00,$00,$00,$00,$00,$00,$10 ; $CF80
    defb $00,$00,$00,$00,$00,$00,$40,$01,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00 ; $CF90

; Physical screen pixel row 175.
    defb $00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$06,$88,$88,$88,$88,$88,$91 ; $CFA0
    defb $11,$11,$11,$11,$11,$60,$00,$01,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00 ; $CFB0

; Physical screen pixel row 183.
    defb $00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$00,$00,$F0,$00,$00,$10 ; $CFC0
    defb $00,$00,$0F,$00,$00,$00,$00,$01,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00 ; $CFD0

; Physical screen pixel row 191.
    defb $00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; $CFE0
    defb $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00 ; $CFF0

CockpitBitmapEnd:
defc CockpitBitmapSize = CockpitBitmapEnd - CockpitBitmap
assert CockpitBitmapEnd-CockpitBitmap = 2048
