; Reconstructed from assets/Elite - 128k.tap; no original binary is included at build time.
; TAP SHA256: d9013872555f448308e0b8a69b624600335384cd38911165bde74a9d11de84d6
; Zero-based TAP data block 5; payload SHA256: 55de3c7f56b1d54434c6b1a7b360174a1f56252e839abdce5463526128e1ff07
; Generated by tools/bootstrap_sources.py. Normal builds assemble this file directly.

; KNOWN DATA: $A910..$A975, 102 bytes.
; VERIFIED DATA: initial 102-byte JAMESON template; copied to ActiveCommanderRecord for a new game and reused as a mutable tape-workflow copy.
; Field-level names remain for later analysis where the exact format is not yet proved.

CommanderTemplateBuffer:
    defb $4A,$41,$4D,$45,$53,$4F,$4E,$00,$00,$00,$00,$00,$00,$00,$00,$00                  ; $A910 JAMESON.........
    defb $00,$00,$00,$00,$E8,$03,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00                  ; $A920 ................
    defb $00,$00,$00,$00,$00,$00,$00,$00,$14,$01,$00,$00,$00,$00,$46,$03                  ; $A930 ..............F.
    defb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$4A,$5A,$48,$02                  ; $A940 ............JZH.
    defb $53,$B7,$38,$AD,$9C,$14,$1D,$15,$05,$03,$11,$12,$1A,$0E,$27,$08                  ; $A950 S.8...........'.
    defb $00,$00,$0A,$19,$00,$00,$3D,$0E,$11,$0C,$00,$00,$00                              ; $A960 ......=......
L_A96D:
    defb $27,$08,$01,$2A,$4D,$8F,$F2,$88,$05                                              ; $A96D '..*M....

CommanderTemplateBufferEnd:
defc CommanderTemplateBufferSize = CommanderTemplateBufferEnd - CommanderTemplateBuffer
assert CommanderTemplateBufferSize = 102
