; Reconstructed from assets/Elite - 128k.tap; no original binary is included at build time.
; TAP SHA256: d9013872555f448308e0b8a69b624600335384cd38911165bde74a9d11de84d6
; Zero-based TAP data block 5; payload SHA256: 55de3c7f56b1d54434c6b1a7b360174a1f56252e839abdce5463526128e1ff07
; Generated by tools/bootstrap_sources.py. Normal builds assemble this file directly.

; KNOWN DATA: $C000..$C2D7, 728 bytes.
; VERIFIED font: startup copies this block to FontRuntime; character lookup uses (code-FontFirstCode)*8.
; The on-tape data is initial content, NOT read-only runtime storage.
; The $C000..$CFFF area is later reused by graphics buffers and temporary stack.
; One glyph per group, top-to-bottom rows, bit 7 is the leftmost pixel.
; Includes letters, digits and custom graphic tiles in punctuation slots.
; The five zero-filled slots after code $7A are NOT part of the startup copy.

; Character code $20 (32); source $C000.
FontBitmap:
    defb $00,$00,$00,$00,$00 ; $C000
L_C005:
    defb $00,$00,$00 ; $C005

; Character code $21 (33); source $C008.
    defb $FF,$80,$40,$40 ; $C008
L_C00C:
    defb $20,$10,$0C,$03 ; $C00C

; Character code $22 (34); source $C010.
L_C010:
    defb $FF,$01,$02,$02,$04,$08,$30,$C0 ; $C010

; Character code $23 (35); source $C018.
    defb $FF,$FF,$7F,$7F,$3F,$1F,$0F,$03 ; $C018

; Character code $24 (36); source $C020.
    defb $FF,$FF,$FE,$FE,$FC,$F8,$F0,$C0 ; $C020

; Character code $25 (37); source $C028.
    defb $00,$7C,$44,$44,$44,$7C,$00,$FF ; $C028

; Character code $26 (38); source $C030.
    defb $C0,$F0,$F8,$FC,$FE,$FE,$FF,$FF ; $C030

; Character code $27 (39); source $C038.
    defb $00,$08,$10,$00,$00,$00,$00,$00 ; $C038

; Character code $28 (40); source $C040.
    defb $00,$04,$08,$08,$08,$08,$04,$00 ; $C040

; Character code $29 (41); source $C048.
    defb $00,$20,$10,$10,$10,$10,$20,$00 ; $C048

; Character code $2A (42); source $C050.
    defb $00,$40,$40,$40,$40,$00,$40,$00 ; $C050

; Character code $2B (43); source $C058.
    defb $01,$01,$01,$01,$01,$01,$01,$FF ; $C058

; Character code $2C (44); source $C060.
    defb $00,$00,$00,$00,$00,$08,$08,$10 ; $C060

; Character code $2D (45); source $C068.
    defb $00,$00,$00,$00,$3E,$00,$00,$00 ; $C068

; Character code $2E (46); source $C070.
    defb $00,$00,$00,$00,$00,$18,$18,$00 ; $C070

; Character code $2F (47); source $C078.
    defb $00,$00,$02,$04,$08,$10,$20,$00 ; $C078

; Character code $30 (48); source $C080.
    defb $00,$3C,$46,$4A,$52,$62,$3C,$00 ; $C080

; Character code $31 (49); source $C088.
    defb $00,$18,$28,$08,$08,$08,$3E,$00 ; $C088

; Character code $32 (50); source $C090.
    defb $00,$3C,$42,$02,$3C,$40,$7E,$00 ; $C090

; Character code $33 (51); source $C098.
    defb $00,$3C,$42,$0C,$02,$42,$3C,$00 ; $C098

; Character code $34 (52); source $C0A0.
    defb $00,$08,$18,$28,$48,$7E,$08,$00 ; $C0A0

; Character code $35 (53); source $C0A8.
    defb $00,$7E,$40,$7C,$02,$42,$3C,$00 ; $C0A8

; Character code $36 (54); source $C0B0.
    defb $00,$3C,$40,$7C,$42,$42,$3C,$00 ; $C0B0

; Character code $37 (55); source $C0B8.
    defb $00,$7E,$02,$04,$08,$10,$10,$00 ; $C0B8

; Character code $38 (56); source $C0C0.
    defb $00,$3C,$42,$3C,$42,$42,$3C,$00 ; $C0C0

; Character code $39 (57); source $C0C8.
    defb $00,$3C,$42,$42,$3E,$02,$3C,$00 ; $C0C8

; Character code $3A (58); source $C0D0.
    defb $00,$00,$00,$10,$00,$00,$10,$00 ; $C0D0

; Character code $3B (59); source $C0D8.
    defb $3F,$3F,$30,$30,$30,$30,$3F,$3F ; $C0D8

; Character code $3C (60); source $C0E0.
    defb $FC,$FC,$00,$00,$00,$00,$FC,$FC ; $C0E0

; Character code $3D (61); source $C0E8.
    defb $30,$30,$30,$30,$3F,$3F,$00,$FF ; $C0E8

; Character code $3E (62); source $C0F0.
L_C0F0:
    defb $00,$00,$00,$00,$FC,$FC,$00,$FF ; $C0F0

; Character code $3F (63); source $C0F8.
    defb $00,$3C,$42,$04,$08,$00,$08,$00 ; $C0F8

; Character code $40 (64); source $C100.
L_C100:
    defb $00,$00,$00,$00,$00,$00 ; $C100
L_C106:
    defb $00,$FF ; $C106

; Character code $41 (65); source $C108.
    defb $00,$3C,$42,$42,$7E,$42,$42,$00 ; $C108

; Character code $42 (66); source $C110.
    defb $00,$7C,$42,$7C,$42,$42,$7C,$00 ; $C110

; Character code $43 (67); source $C118.
    defb $00,$3C,$42,$40,$40,$42,$3C,$00 ; $C118

; Character code $44 (68); source $C120.
    defb $00,$78,$44,$42,$42,$44,$78,$00 ; $C120

; Character code $45 (69); source $C128.
    defb $00,$7E,$40,$7C,$40,$40,$7E,$00 ; $C128

; Character code $46 (70); source $C130.
    defb $00,$7E,$40,$7C,$40,$40,$40,$00 ; $C130

; Character code $47 (71); source $C138.
    defb $00,$3C,$42,$40,$4E,$42,$3C,$00 ; $C138

; Character code $48 (72); source $C140.
    defb $00,$42,$42,$7E,$42,$42,$42,$00 ; $C140

; Character code $49 (73); source $C148.
    defb $00,$3E,$08,$08,$08,$08,$3E,$00 ; $C148

; Character code $4A (74); source $C150.
    defb $00,$02,$02,$02,$42,$42,$3C,$00 ; $C150

; Character code $4B (75); source $C158.
    defb $00,$44,$48,$70,$48,$44,$42,$00 ; $C158

; Character code $4C (76); source $C160.
    defb $00,$40,$40,$40,$40,$40,$7E,$00 ; $C160

; Character code $4D (77); source $C168.
    defb $00,$42,$66,$5A,$42,$42,$42,$00 ; $C168

; Character code $4E (78); source $C170.
    defb $00,$42,$62,$52,$4A,$46,$42,$00 ; $C170

; Character code $4F (79); source $C178.
    defb $00,$3C,$42,$42,$42,$42,$3C,$00 ; $C178

; Character code $50 (80); source $C180.
    defb $00,$7C,$42,$42,$7C,$40,$40,$00 ; $C180

; Character code $51 (81); source $C188.
    defb $00,$3C,$42,$42,$52,$4A,$3C,$00 ; $C188

; Character code $52 (82); source $C190.
    defb $00,$7C,$42,$42,$7C,$44,$42,$00 ; $C190

; Character code $53 (83); source $C198.
    defb $00,$3C,$40,$3C,$02,$42,$3C,$00 ; $C198

; Character code $54 (84); source $C1A0.
    defb $00,$FE,$10,$10,$10,$10,$10,$00 ; $C1A0

; Character code $55 (85); source $C1A8.
    defb $00,$42,$42,$42,$42,$42,$3C,$00 ; $C1A8

; Character code $56 (86); source $C1B0.
    defb $00,$42,$42,$42,$42,$24,$18,$00 ; $C1B0

; Character code $57 (87); source $C1B8.
    defb $00,$42,$42,$42,$42,$5A,$24,$00 ; $C1B8

; Character code $58 (88); source $C1C0.
    defb $00,$42,$24,$18,$18,$24,$42,$00 ; $C1C0

; Character code $59 (89); source $C1C8.
    defb $00,$82,$44,$28,$10,$10,$10,$00 ; $C1C8

; Character code $5A (90); source $C1D0.
    defb $00,$7E,$04,$08,$10,$20,$7E,$00 ; $C1D0

; Character code $5B (91); source $C1D8.
    defb $FF,$FF,$C0,$C0,$C0,$FF,$FF,$00 ; $C1D8

; Character code $5C (92); source $C1E0.
    defb $F9,$F9,$01,$01,$01,$F9,$F9,$19 ; $C1E0

; Character code $5D (93); source $C1E8.
    defb $00,$00,$00,$FF,$FF,$00,$00,$FF ; $C1E8

; Character code $5E (94); source $C1F0.
    defb $19,$19,$19,$F9,$F9,$01,$01,$FF ; $C1F0

; Character code $5F (95); source $C1F8.
    defb $01,$01,$01,$01,$01,$01,$01,$01 ; $C1F8

; Character code $60 (96); source $C200.
    defb $00,$1C ; $C200
L_C202:
    defb $22,$78,$20,$20,$7E,$00 ; $C202

; Character code $61 (97); source $C208.
    defb $00,$00,$38,$04,$3C,$44,$3C,$00 ; $C208

; Character code $62 (98); source $C210.
    defb $00,$20,$20,$3C,$22,$22,$3C,$00 ; $C210

; Character code $63 (99); source $C218.
    defb $00,$00,$1C,$20,$20,$20,$1C,$00 ; $C218

; Character code $64 (100); source $C220.
    defb $00,$04,$04,$3C,$44,$44,$3C,$00 ; $C220

; Character code $65 (101); source $C228.
    defb $00,$00,$38,$44,$78,$40,$3C,$00 ; $C228

; Character code $66 (102); source $C230.
    defb $00,$0C,$10,$18,$10,$10,$10,$00 ; $C230

; Character code $67 (103); source $C238.
    defb $00,$00,$3C,$44,$44,$3C,$04,$38 ; $C238

; Character code $68 (104); source $C240.
    defb $00,$40,$40,$78,$44,$44,$44,$00 ; $C240

; Character code $69 (105); source $C248.
    defb $00,$10,$00,$30,$10,$10,$38,$00 ; $C248

; Character code $6A (106); source $C250.
    defb $00,$04,$00,$04,$04,$04,$24,$18 ; $C250

; Character code $6B (107); source $C258.
    defb $00,$20,$28,$30,$30,$28,$24,$00 ; $C258

; Character code $6C (108); source $C260.
    defb $00,$10,$10,$10,$10,$10,$0C,$00 ; $C260

; Character code $6D (109); source $C268.
    defb $00,$00,$68,$54,$54,$54,$54,$00 ; $C268

; Character code $6E (110); source $C270.
    defb $00,$00,$78,$44,$44,$44,$44,$00 ; $C270

; Character code $6F (111); source $C278.
    defb $00,$00,$38,$44,$44,$44,$38,$00 ; $C278

; Character code $70 (112); source $C280.
    defb $00,$00,$78,$44,$44,$78,$40,$40 ; $C280

; Character code $71 (113); source $C288.
    defb $00,$00,$3C,$44,$44,$3C,$04,$06 ; $C288

; Character code $72 (114); source $C290.
    defb $00,$00,$1C,$20,$20,$20,$20,$00 ; $C290

; Character code $73 (115); source $C298.
    defb $00,$00,$38,$40,$38,$04,$78,$00 ; $C298

; Character code $74 (116); source $C2A0.
    defb $00,$10,$38,$10,$10,$10,$0C,$00 ; $C2A0

; Character code $75 (117); source $C2A8.
    defb $00,$00,$44,$44,$44,$44,$38,$00 ; $C2A8

; Character code $76 (118); source $C2B0.
    defb $00,$00,$44,$44,$28,$28,$10,$00 ; $C2B0

; Character code $77 (119); source $C2B8.
    defb $00,$00,$44,$54,$54,$54,$28,$00 ; $C2B8

; Character code $78 (120); source $C2C0.
    defb $00,$00,$44,$28,$10,$28,$44,$00 ; $C2C0

; Character code $79 (121); source $C2C8.
    defb $00,$00,$44,$44,$44,$3C,$04,$38 ; $C2C8

; Character code $7A (122); source $C2D0.
    defb $00,$00,$7C,$08,$10,$20,$7C,$00 ; $C2D0

FontBitmapEnd:
defc FontBitmapSize = FontBitmapEnd - FontBitmap
assert FontBitmapEnd-FontBitmap = 728
defc FontGlyphCount = FontBitmapSize / FontGlyphHeight
defc FontRuntimeEnd = FontRuntime + FontBitmapSize
assert FontRuntimeEnd = GameLoadAddress
assert FontGlyphCount * FontGlyphHeight = FontBitmapSize
assert FontFirstCode + FontGlyphCount = $7B
