; Reconstructed from assets/Elite - 128k.tap; no original binary is included at build time.
; TAP SHA256: d9013872555f448308e0b8a69b624600335384cd38911165bde74a9d11de84d6
; Zero-based TAP data block 5; payload SHA256: 55de3c7f56b1d54434c6b1a7b360174a1f56252e839abdce5463526128e1ff07
; Generated by tools/analyze_ship_blueprints.py; tools/bootstrap_sources.py uses the same renderer.

; VERIFIED DATA: 19 four-byte dispatch entries, structured ship blueprint
; headers and geometry, followed by text/control-token handler pointers.
; Each vertex is 6 bytes; each edge and face is 4 bytes.

ShipBlueprintsAndDispatchTables:
ShipBlueprintTable:
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipCoriolisStationBlueprint
IF !SHIP_ADDER
    defb $00 ; ID 0: Coriolis station
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipMissileBlueprint
IF !SHIP_ADDER
    defb $00 ; ID 1: Missile
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipEscapeCapsuleBlueprint
IF !SHIP_ADDER
    defb $01 ; ID 2: Escape capsule
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipAlloyPlateBlueprint
IF !SHIP_ADDER
    defb $01 ; ID 3: Alloy plate
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipCargoCanisterBlueprint
IF !SHIP_ADDER
    defb $01 ; ID 4: Cargo canister
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipSplinterBlueprint
IF !SHIP_ADDER
    defb $01 ; ID 5: Splinter
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipAsteroidBlueprint
IF !SHIP_ADDER
    defb $01 ; ID 6: Asteroid
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipRockHermitBlueprint
IF !SHIP_ADDER
    defb $02 ; ID 7: Rock hermit
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipViperBlueprint
IF !SHIP_ADDER
    defb $02 ; ID 8: Viper
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipCobraMkIIITraderBlueprint
IF !SHIP_ADDER
    defb $02 ; ID 9: Cobra Mk III (trader record)
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipPythonTraderBlueprint
IF !SHIP_ADDER
    defb $02 ; ID 10: Python (trader record)
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipPythonPirateBlueprint
IF !SHIP_ADDER
    defb $03 ; ID 11: Python (pirate record)
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipCobraMkIIIPirateBlueprint
IF !SHIP_ADDER
    defb $03 ; ID 12: Cobra Mk III (pirate record)
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipAspMkIIBlueprint
IF !SHIP_ADDER
    defb $03 ; ID 13: Asp Mk II
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipFerDeLanceBlueprint
IF !SHIP_ADDER
    defb $03 ; ID 14: Fer-de-Lance
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipThargoidBlueprint
IF !SHIP_ADDER
    defb $03 ; ID 15: Thargoid
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipSidewinderBlueprint
IF !SHIP_ADDER
    defb $04 ; ID 16: Sidewinder
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
IF SHIP_ADDER
    defw ShipAdderBlueprint
ELSE
    defw ShipKraitBlueprint
ENDIF
IF !SHIP_ADDER
    defb $04 ; ID 17: Krait
ENDIF
IF !SHIP_ADDER
    defb $C3
ENDIF
    defw ShipThargonBlueprint
IF !SHIP_ADDER
    defb $04 ; ID 18: Thargon
ENDIF
ShipBlueprintTableEnd:
defc ShipBlueprintCount = 19
IF SHIP_ADDER
assert ShipBlueprintTableEnd-ShipBlueprintTable = ShipBlueprintCount*2
ELSE
assert ShipBlueprintTableEnd-ShipBlueprintTable = ShipBlueprintCount*4
ENDIF

; Blueprint ID 13: Asp Mk II; original address $61CC.
ShipAspMkIIBlueprint:
    defb $00 ; canister/commodity flags; low nibble is maximum canisters
    defb 60 ; target size
    defb $FA ; agility / rotation limit
    defb 19 ; vertices
    defb 28 ; edges
    defb 12 ; faces
    defb 40 ; maximum speed
    defb 150 ; energy
    defw 200 ; bounty in tenths of a credit
    defb $01 ; partially decoded property byte
    defb 24 ; visibility distance
    defw ShipAspMkIIVertices-ShipAspMkIIBlueprint
    defw ShipAspMkIIEdges-ShipAspMkIIBlueprint
    defw ShipAspMkIIFaces-ShipAspMkIIBlueprint
    defb $8C ; behaviour flags
    defb $01 ; partially decoded property byte
    defb 8 ; gun vertex
    defb $40 ; partially decoded property byte
    defb 3 ; normal scaling exponent
assert $-ShipAspMkIIBlueprint = 23
ShipAspMkIIVertices:
    defb $00,$12,$00,$56,$01,$22,$00,$09,$2D,$7F,$12,$BB,$2B,$00,$2D,$3F,$16,$BB,$45,$03,$00,$5F,$16,$79 ; $61E3
    defb $2B,$0E,$1C,$5F,$01,$77,$2B,$00,$2D,$BF,$25,$BB,$45,$03,$00,$DF,$25,$8A,$2B,$0E,$1C,$DF,$02,$88 ; $61FB
    defb $1A,$07,$49,$5F,$04,$79,$1A,$07,$49,$DF,$04,$8A,$2B,$0E,$1C,$1F,$34,$69,$2B,$0E,$1C,$9F,$34,$5A ; $6213
    defb $00,$09,$2D,$3F,$35,$6B,$11,$00,$2D,$AA,$BB,$BB,$11,$00,$2D,$29,$BB,$BB,$00,$04,$2D,$6A,$BB,$BB ; $622B
    defb $00,$04,$2D,$28,$BB,$BB,$00,$07,$49,$4A,$04,$04,$00,$07,$53,$4A,$04,$04 ; $6243
assert $-ShipAspMkIIVertices = 114
ShipAspMkIIEdges:
    defb $16,$00,$01,$12,$16,$00,$04,$01,$16,$00,$07,$02,$1F,$01,$02,$1B ; $6255
    defb $1F,$02,$03,$16,$10,$03,$08,$79,$1F,$08,$09,$04,$10,$06,$09,$8A ; $6265
    defb $1F,$05,$06,$25,$1F,$01,$05,$2B,$1F,$03,$04,$17,$1F,$04,$08,$07 ; $6275
    defb $1F,$06,$07,$28,$1F,$07,$09,$08,$1F,$02,$0C,$6B,$1F,$05,$0C,$5B ; $6285
    defb $16,$0A,$0C,$36,$16,$0B,$0C,$35,$16,$0A,$0B,$34,$1F,$06,$0B,$5A ; $6295
    defb $1F,$09,$0B,$4A,$1F,$03,$0A,$69,$1F,$08,$0A,$49,$0A,$0D,$0F,$BB ; $62A5
    defb $09,$0F,$0E,$BB,$08,$0E,$10,$BB,$08,$10,$0D,$BB,$0A,$12,$11,$04 ; $62B5
assert $-ShipAspMkIIEdges = 112
ShipAspMkIIFaces:
    defb $00,$23,$05,$5F,$08,$26,$07,$7F,$08,$26,$07,$FF,$00,$18,$01,$36 ; $62C5
    defb $00,$2B,$13,$1F,$06,$1C,$02,$BF,$06,$1C,$02,$3F,$3B,$40,$1F,$5F ; $62D5
    defb $3B,$40,$1F,$DF,$50,$2E,$32,$1F,$50,$2E,$32,$9F,$00,$00,$5A,$3F ; $62E5
assert $-ShipAspMkIIFaces = 48

; Blueprint ID 7: Rock hermit; original address $62F5.
ShipRockHermitBlueprint:
    defb $07 ; canister/commodity flags; low nibble is maximum canisters
    defb 80 ; target size
    defb $50 ; agility / rotation limit
    defb 9 ; vertices
    defb 21 ; edges
    defb 14 ; faces
    defb 30 ; maximum speed
    defb 180 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $52 ; partially decoded property byte
    defb 50 ; visibility distance
    defw ShipAsteroidVertices-ShipRockHermitBlueprint
    defw ShipAsteroidEdges-ShipRockHermitBlueprint
    defw ShipAsteroidFaces-ShipRockHermitBlueprint
    defb $A1 ; behaviour flags
    defb $01 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $00 ; partially decoded property byte
    defb 1 ; normal scaling exponent
assert $-ShipRockHermitBlueprint = 23
; Geometry is shared with Asteroid.

; Blueprint ID 6: Asteroid; original address $630C.
ShipAsteroidBlueprint:
    defb $00 ; canister/commodity flags; low nibble is maximum canisters
    defb 80 ; target size
    defb $00 ; agility / rotation limit
    defb 9 ; vertices
    defb 21 ; edges
    defb 14 ; faces
    defb 30 ; maximum speed
    defb 60 ; energy
    defw 5 ; bounty in tenths of a credit
    defb $00 ; partially decoded property byte
    defb 50 ; visibility distance
    defw ShipAsteroidVertices-ShipAsteroidBlueprint
    defw ShipAsteroidEdges-ShipAsteroidBlueprint
    defw ShipAsteroidFaces-ShipAsteroidBlueprint
    defb $00 ; behaviour flags
    defb $01 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $19 ; partially decoded property byte
    defb 0 ; normal scaling exponent
assert $-ShipAsteroidBlueprint = 23
ShipAsteroidVertices:
    defb $00,$50,$00,$1F,$FF,$FF,$50,$0A,$00,$DF,$FF,$FF,$00,$50,$00,$5F,$FF,$FF,$46,$28,$00,$5F,$FF,$FF ; $6323
    defb $3C,$32,$00,$1F,$65,$DC,$32,$00,$3C,$1F,$FF,$FF,$28,$00,$46,$9F,$10,$32,$00,$1E,$4B,$3F,$FF,$FF ; $633B
    defb $00,$32,$3C,$7F,$98,$BA ; $6353
assert $-ShipAsteroidVertices = 54
ShipAsteroidEdges:
    defb $1F,$00,$01,$72,$1F,$00,$04,$D6,$1F,$03,$04,$C5,$1F,$02,$03,$B4 ; $6359
    defb $1F,$01,$02,$A3,$1F,$01,$06,$32,$1F,$02,$06,$31,$1F,$02,$05,$41 ; $6369
    defb $1F,$05,$06,$10,$1F,$00,$05,$60,$1F,$03,$05,$54,$1F,$00,$06,$20 ; $6379
    defb $1F,$04,$05,$65,$1F,$01,$08,$A8,$1F,$01,$07,$87,$1F,$00,$07,$D7 ; $6389
    defb $1F,$04,$07,$DC,$1F,$03,$07,$C9,$1F,$03,$08,$B9,$1F,$02,$08,$BA ; $6399
    defb $1F,$07,$08,$98 ; $63A9
assert $-ShipAsteroidEdges = 84
ShipAsteroidFaces:
    defb $09,$42,$51,$1F,$09,$42,$51,$5F,$48,$40,$1F,$9F,$40,$49,$2F,$DF ; $63AD
    defb $2D,$4F,$41,$5F,$87,$0F,$23,$1F,$26,$4C,$46,$1F,$42,$3B,$27,$BF ; $63BD
    defb $43,$0F,$50,$FF,$42,$0E,$4B,$7F,$46,$50,$28,$FF,$3A,$66,$33,$7F ; $63CD
    defb $51,$09,$43,$3F,$2F,$5E,$3F,$3F ; $63DD
assert $-ShipAsteroidFaces = 56

; Blueprint ID 4: Cargo canister; original address $63E5.
ShipCargoCanisterBlueprint:
    defb $00 ; canister/commodity flags; low nibble is maximum canisters
    defb 20 ; target size
    defb $00 ; agility / rotation limit
    defb 10 ; vertices
    defb 15 ; edges
    defb 7 ; faces
    defb 15 ; maximum speed
    defb 17 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $00 ; partially decoded property byte
    defb 12 ; visibility distance
    defw ShipCargoCanisterVertices-ShipCargoCanisterBlueprint
    defw ShipCargoCanisterEdges-ShipCargoCanisterBlueprint
    defw ShipCargoCanisterFaces-ShipCargoCanisterBlueprint
    defb $00 ; behaviour flags
    defb $02 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $1F ; partially decoded property byte
    defb 0 ; normal scaling exponent
assert $-ShipCargoCanisterBlueprint = 23
ShipCargoCanisterVertices:
    defb $18,$10,$00,$1F,$10,$55,$18,$05,$0F,$1F,$10,$22,$18,$0D ; $63FC
L_640A:
    defb $09,$5F,$20,$33,$18,$0D,$09,$7F,$30,$44,$18,$05,$0F,$3F,$40,$55,$18,$10,$00,$9F,$51,$66,$18,$05 ; $640A
    defb $0F,$9F,$21,$66,$18,$0D,$09,$DF,$32,$66,$18,$0D,$09,$FF,$43,$66,$18,$05,$0F,$BF,$54,$66 ; $6422
assert $-ShipCargoCanisterVertices = 60
ShipCargoCanisterEdges:
    defb $1F,$00,$01,$10,$1F,$01,$02,$20,$1F,$02,$03,$30,$1F,$03,$04,$40 ; $6438
    defb $1F,$00,$04,$50,$1F,$00,$05,$51,$1F,$01,$06,$21,$1F,$02,$07,$32 ; $6448
    defb $1F,$03,$08,$43,$1F,$04,$09,$54,$1F,$05,$06,$61,$1F,$06,$07,$62 ; $6458
    defb $1F,$07,$08,$63,$1F,$08,$09,$64,$1F,$09,$05,$65 ; $6468
assert $-ShipCargoCanisterEdges = 60
ShipCargoCanisterFaces:
    defb $60,$00,$00,$1F,$00,$29,$1E,$1F,$00,$12,$30,$5F,$00,$33,$00,$5F ; $6474
    defb $00,$12,$30,$7F,$00,$29,$1E,$3F,$60,$00,$00,$9F ; $6484
assert $-ShipCargoCanisterFaces = 28

; Blueprint ID 9: Cobra Mk III (trader record); original address $6490.
ShipCobraMkIIITraderBlueprint:
    defb $03 ; canister/commodity flags; low nibble is maximum canisters
    defb 95 ; target size
    defb $8C ; agility / rotation limit
    defb 28 ; vertices
    defb 38 ; edges
    defb 13 ; faces
    defb 28 ; maximum speed
    defb 150 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $04 ; partially decoded property byte
    defb 50 ; visibility distance
    defw ShipCobraMkIIIPirateVertices-ShipCobraMkIIITraderBlueprint
    defw ShipCobraMkIIIPirateEdges-ShipCobraMkIIITraderBlueprint
    defw ShipCobraMkIIIPirateFaces-ShipCobraMkIIITraderBlueprint
    defb $A0 ; behaviour flags
    defb $01 ; partially decoded property byte
    defb 21 ; gun vertex
    defb $00 ; partially decoded property byte
    defb 2 ; normal scaling exponent
assert $-ShipCobraMkIIITraderBlueprint = 23
; Geometry is shared with Cobra Mk III (pirate record).

; Blueprint ID 12: Cobra Mk III (pirate record); original address $64A7.
ShipCobraMkIIIPirateBlueprint:
    defb $01 ; canister/commodity flags; low nibble is maximum canisters
    defb 95 ; target size
    defb $A0 ; agility / rotation limit
    defb 28 ; vertices
    defb 38 ; edges
    defb 13 ; faces
    defb 28 ; maximum speed
    defb 150 ; energy
    defw 175 ; bounty in tenths of a credit
    defb $02 ; partially decoded property byte
    defb 50 ; visibility distance
    defw ShipCobraMkIIIPirateVertices-ShipCobraMkIIIPirateBlueprint
    defw ShipCobraMkIIIPirateEdges-ShipCobraMkIIIPirateBlueprint
    defw ShipCobraMkIIIPirateFaces-ShipCobraMkIIIPirateBlueprint
    defb $8C ; behaviour flags
    defb $0A ; partially decoded property byte
    defb 21 ; gun vertex
    defb $80 ; partially decoded property byte
    defb 3 ; normal scaling exponent
assert $-ShipCobraMkIIIPirateBlueprint = 23
ShipCobraMkIIIPirateVertices:
    defb $20,$00,$4C,$1F,$FF,$FF,$20,$00,$4C,$9F,$FF,$FF,$00,$1A,$18,$1F,$FF,$FF,$78,$03,$08,$FF,$73,$AA ; $64BE
    defb $78,$03,$08,$7F,$84,$CC,$58,$10,$28,$BF,$FF,$FF,$58,$10,$28,$3F,$FF,$FF,$80,$08,$28,$7F,$98,$CC ; $64D6
    defb $80,$08,$28,$FF,$97,$AA,$00,$1A,$28,$3F,$65,$99,$20,$18,$28,$FF,$A9,$BB,$20,$18,$28,$7F,$B9,$CC ; $64EE
    defb $24,$08,$28,$B4,$99,$99,$08,$0C,$28,$B4,$99,$99,$08,$0C,$28,$34,$99,$99,$24,$08,$28,$34,$99,$99 ; $6506
    defb $24,$0C,$28,$74,$99,$99,$08,$10,$28,$74,$99,$99,$08,$10,$28,$F4,$99,$99,$24,$0C,$28,$F4,$99,$99 ; $651E
    defb $00,$00,$4C,$06,$B0,$BB,$00,$00,$5A,$1F,$B0,$BB,$50,$06,$28,$E8,$99,$99,$50,$06,$28,$A8,$99,$99 ; $6536
    defb $58,$00,$28,$A6,$99,$99,$50,$06,$28,$28,$99,$99,$58,$00,$28,$26,$99,$99,$50,$06,$28,$68,$99,$99 ; $654E
assert $-ShipCobraMkIIIPirateVertices = 168
ShipCobraMkIIIPirateEdges:
    defb $1F,$00,$01,$B0,$1F,$00,$04,$C4,$1F,$01,$03,$A3,$1F,$03,$08,$A7 ; $6566
    defb $1F,$04,$07,$C8,$1F,$06,$07,$98,$1F,$06,$09,$96,$1F,$05,$09,$95 ; $6576
    defb $1F,$05,$08,$97,$1F,$02,$05,$51,$1F,$02,$06,$62,$1F,$03,$05,$73 ; $6586
    defb $1F,$04,$06,$84,$1F,$01,$02,$10,$1F,$00,$02,$20,$1F,$08,$0A,$A9 ; $6596
    defb $1F,$0A,$0B,$B9,$1F,$07,$0B,$C9,$1F,$01,$0A,$BA,$1F,$00,$0B,$CB ; $65A6
    defb $1D,$01,$05,$31,$1D,$00,$06,$42,$06,$14,$15,$B0,$14,$0C,$0D,$99 ; $65B6
    defb $14,$12,$13,$99,$14,$0E,$0F,$99,$14,$10,$11,$99,$13,$0F,$10,$99 ; $65C6
    defb $11,$0E,$11,$99,$13,$0D,$12,$99,$13,$0C,$13,$99,$1E,$02,$09,$65 ; $65D6
    defb $06,$16,$18,$99,$06,$17,$18,$99,$08,$16,$17,$99,$06,$19,$1A,$99 ; $65E6
    defb $06,$1A,$1B,$99,$08,$19,$1B,$99 ; $65F6
assert $-ShipCobraMkIIIPirateEdges = 152
ShipCobraMkIIIPirateFaces:
    defb $00,$3E,$1F,$1F,$12,$37,$10,$9F,$12,$37,$10,$1F,$10,$34,$0E,$9F ; $65FE
    defb $10,$34,$0E,$1F,$0E,$2F,$00,$9F,$0E,$2F,$00,$1F,$3D,$66,$00,$9F ; $660E
    defb $3D,$66,$00,$1F,$00,$00,$50,$3F,$07,$2A,$09,$DF,$00,$1E,$06,$5F ; $661E
    defb $07,$2A,$09,$5F ; $662E
assert $-ShipCobraMkIIIPirateFaces = 52

; Blueprint ID 2: Escape capsule; original address $6632.
ShipEscapeCapsuleBlueprint:
    defb $20 ; canister/commodity flags; low nibble is maximum canisters
    defb 16 ; target size
    defb $FF ; agility / rotation limit
    defb 4 ; vertices
    defb 6 ; edges
    defb 4 ; faces
    defb 8 ; maximum speed
    defb 17 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $00 ; partially decoded property byte
    defb 8 ; visibility distance
    defw ShipEscapeCapsuleVertices-ShipEscapeCapsuleBlueprint
    defw ShipEscapeCapsuleEdges-ShipEscapeCapsuleBlueprint
    defw ShipEscapeCapsuleFaces-ShipEscapeCapsuleBlueprint
    defb $01 ; behaviour flags
    defb $04 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $32 ; partially decoded property byte
    defb 0 ; normal scaling exponent
assert $-ShipEscapeCapsuleBlueprint = 23
ShipEscapeCapsuleVertices:
    defb $07,$00,$24,$9F,$12,$33,$07,$0E,$0C,$FF,$02,$33,$07,$0E,$0C,$BF,$01,$33,$15,$00,$00,$1F,$01,$22 ; $6649
assert $-ShipEscapeCapsuleVertices = 24
ShipEscapeCapsuleEdges:
    defb $1F,$00,$01,$23,$1F,$01,$02,$03,$1F,$02,$03,$01,$1F,$03,$00,$12 ; $6661
    defb $1F,$00,$02,$13,$1F,$03,$01,$02 ; $6671
assert $-ShipEscapeCapsuleEdges = 24
ShipEscapeCapsuleFaces:
    defb $34,$00,$7A,$3F,$27,$67,$1E,$1F,$27,$67,$1E,$5F,$70,$00,$00,$9F ; $6679
assert $-ShipEscapeCapsuleFaces = 16

; Blueprint ID 14: Fer-de-Lance; original address $6689.
ShipFerDeLanceBlueprint:
    defb $00 ; canister/commodity flags; low nibble is maximum canisters
    defb 40 ; target size
    defb $FF ; agility / rotation limit
    defb 19 ; vertices
    defb 27 ; edges
    defb 10 ; faces
    defb 30 ; maximum speed
    defb 160 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $02 ; partially decoded property byte
    defb 30 ; visibility distance
    defw ShipFerDeLanceVertices-ShipFerDeLanceBlueprint
    defw ShipFerDeLanceEdges-ShipFerDeLanceBlueprint
    defw ShipFerDeLanceFaces-ShipFerDeLanceBlueprint
    defb $82 ; behaviour flags
    defb $01 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $00 ; partially decoded property byte
    defb 3 ; normal scaling exponent
assert $-ShipFerDeLanceBlueprint = 23
ShipFerDeLanceVertices:
    defb $00,$0E,$6C,$5F,$01,$59,$28,$0E,$04,$FF,$12,$99,$0C,$0E,$34,$FF,$23,$99,$0C,$0E,$34,$7F,$34,$99 ; $66A0
    defb $28,$0E,$04,$7F,$45,$99,$28,$0E,$04,$BC,$01,$26,$0C,$02,$34,$BC,$23,$67,$0C,$02,$34,$3C,$34,$78 ; $66B8
    defb $28,$0E,$04,$3C,$04,$58,$00,$12,$14,$2F,$06,$78,$03,$0B,$61,$CB,$00,$00,$1A,$08,$12,$89,$00,$00 ; $66D0
    defb $10,$0E,$04,$AB,$00,$00,$03,$0B,$61,$4B,$00,$00,$1A,$08,$12,$09,$00,$00,$10,$0E,$04,$2B,$00,$00 ; $66E8
    defb $00,$0E,$14,$6C,$99,$99,$0E,$0E,$2C,$CC,$99,$99,$0E,$0E,$2C,$4C,$99,$99 ; $6700
assert $-ShipFerDeLanceVertices = 114
ShipFerDeLanceEdges:
    defb $1F,$00,$01,$19,$1F,$01,$02,$29,$1F,$02,$03,$39,$1F,$03,$04,$49 ; $6712
    defb $1F,$00,$04,$59,$1C,$00,$05,$01,$1C,$05,$06,$26,$1C,$06,$07,$37 ; $6722
    defb $1C,$07,$08,$48,$1C,$00,$08,$05,$0F,$05,$09,$06,$0B,$06,$09,$67 ; $6732
    defb $0B,$07,$09,$78,$0F,$08,$09,$08,$0E,$01,$05,$12,$0E,$02,$06,$23 ; $6742
    defb $0E,$03,$07,$34,$0E,$04,$08,$45,$08,$0A,$0B,$00,$09,$0B,$0C,$00 ; $6752
    defb $0B,$0A,$0C,$00,$08,$0D,$0E,$00,$09,$0E,$0F,$00,$0B,$0D,$0F,$00 ; $6762
    defb $0C,$10,$11,$99,$0C,$10,$12,$99,$08,$11,$12,$99 ; $6772
assert $-ShipFerDeLanceEdges = 108
ShipFerDeLanceFaces:
    defb $00,$18,$06,$1C,$44,$00,$18,$9F,$3F,$00,$25,$BF,$00,$00,$68,$3F ; $677E
    defb $3F,$00,$25,$3F,$44,$00,$18,$1F,$0C,$2E,$13,$BC,$00,$2D,$16,$BC ; $678E
    defb $0C,$2E,$16,$3C,$00,$1C,$00,$5F ; $679E
assert $-ShipFerDeLanceFaces = 40

; Blueprint ID 1: Missile; original address $67A6.
ShipMissileBlueprint:
    defb $00 ; canister/commodity flags; low nibble is maximum canisters
    defb 40 ; target size
    defb $00 ; agility / rotation limit
    defb 17 ; vertices
    defb 24 ; edges
    defb 9 ; faces
    defb 44 ; maximum speed
    defb 2 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $00 ; partially decoded property byte
    defb 14 ; visibility distance
    defw ShipMissileVertices-ShipMissileBlueprint
    defw ShipMissileEdges-ShipMissileBlueprint
    defw ShipMissileFaces-ShipMissileBlueprint
    defb $00 ; behaviour flags
    defb $02 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $C0 ; partially decoded property byte
    defb 1 ; normal scaling exponent
assert $-ShipMissileBlueprint = 23
ShipMissileVertices:
    defb $00,$00,$44,$1F,$10,$32,$08,$08,$24,$5F,$21,$54,$08,$08,$24,$1F,$32,$74,$08,$08,$24,$9F,$30,$76 ; $67BD
    defb $08,$08,$24,$DF,$10,$65,$08,$08,$2C,$3F,$74,$88,$08,$08,$2C,$7F,$54,$88,$08,$08,$2C,$FF,$65,$88 ; $67D5
    defb $08,$08,$2C,$BF,$76,$88,$0C,$0C,$2C,$28,$74,$88,$0C,$0C,$2C,$68,$54,$88,$0C,$0C,$2C,$E8,$65,$88 ; $67ED
    defb $0C,$0C,$2C,$A8,$76,$88,$08,$08,$0C,$A8,$76,$77,$08,$08,$0C,$E8,$65,$66,$08,$08,$0C,$28,$74,$77 ; $6805
    defb $08,$08,$0C,$68,$54,$55 ; $681D
assert $-ShipMissileVertices = 102
ShipMissileEdges:
    defb $1F,$00,$01,$21,$1F,$00,$02,$32,$1F,$00,$03,$30,$1F,$00,$04,$10 ; $6823
    defb $1F,$01,$02,$24,$1F,$01,$04,$51,$1F,$03,$04,$60,$1F,$02,$03,$73 ; $6833
    defb $1F,$02,$05,$74,$1F,$01,$06,$54,$1F,$04,$07,$65,$1F,$03,$08,$76 ; $6843
    defb $1F,$07,$08,$86,$1F,$05,$08,$87,$1F,$05,$06,$84,$1F,$06,$07,$85 ; $6853
    defb $08,$06,$0A,$85,$08,$05,$09,$87,$08,$08,$0C,$87,$08,$07,$0B,$85 ; $6863
    defb $08,$09,$0F,$74,$08,$0A,$10,$54,$08,$0C,$0D,$76,$08,$0B,$0E,$65 ; $6873
assert $-ShipMissileEdges = 96
ShipMissileFaces:
    defb $40,$00,$10,$9F,$00,$40,$10,$5F,$40,$00,$10,$1F,$00,$40,$10,$1F ; $6883
    defb $20,$00,$00,$1F,$00,$20,$00,$5F,$20,$00,$00,$9F,$00,$20,$00,$1F ; $6893
    defb $00,$00,$B0,$3F ; $68A3
assert $-ShipMissileFaces = 36

; Blueprint ID 3: Alloy plate; original address $68A7.
ShipAlloyPlateBlueprint:
    defb $80 ; canister/commodity flags; low nibble is maximum canisters
    defb 10 ; target size
    defb $00 ; agility / rotation limit
    defb 4 ; vertices
    defb 4 ; edges
    defb 0 ; faces
    defb 16 ; maximum speed
    defb 16 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $00 ; partially decoded property byte
    defb 12 ; visibility distance
    defw ShipAlloyPlateVertices-ShipAlloyPlateBlueprint
    defw ShipAlloyPlateEdges-ShipAlloyPlateBlueprint
    defw 0 ; no face normals
    defb $00 ; behaviour flags
    defb $03 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $20 ; partially decoded property byte
    defb 0 ; normal scaling exponent
assert $-ShipAlloyPlateBlueprint = 23
ShipAlloyPlateVertices:
    defb $0F,$16,$09,$FF,$FF,$FF,$0F,$26,$09,$BF,$FF,$FF,$13,$20,$0B,$14,$FF,$FF,$0A,$2E,$06,$54,$FF,$FF ; $68BE
assert $-ShipAlloyPlateVertices = 24
ShipAlloyPlateEdges:
    defb $1F,$00,$01,$FF,$10,$01,$02,$FF,$14,$02,$03,$FF,$10,$03,$00,$FF ; $68D6
assert $-ShipAlloyPlateEdges = 16

; Blueprint ID 10: Python (trader record); original address $68E6.
ShipPythonTraderBlueprint:
    defb $05 ; canister/commodity flags; low nibble is maximum canisters
    defb 80 ; target size
    defb $82 ; agility / rotation limit
    defb 11 ; vertices
    defb 26 ; edges
    defb 13 ; faces
    defb 20 ; maximum speed
    defb 250 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $00 ; partially decoded property byte
    defb 40 ; visibility distance
    defw ShipPythonPirateVertices-ShipPythonTraderBlueprint
    defw ShipPythonPirateEdges-ShipPythonTraderBlueprint
    defw ShipPythonPirateFaces-ShipPythonTraderBlueprint
    defb $A0 ; behaviour flags
    defb $00 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $00 ; partially decoded property byte
    defb 2 ; normal scaling exponent
assert $-ShipPythonTraderBlueprint = 23
; Geometry is shared with Python (pirate record).

; Blueprint ID 11: Python (pirate record); original address $68FD.
ShipPythonPirateBlueprint:
    defb $02 ; canister/commodity flags; low nibble is maximum canisters
    defb 80 ; target size
    defb $96 ; agility / rotation limit
    defb 11 ; vertices
    defb 26 ; edges
    defb 13 ; faces
    defb 20 ; maximum speed
    defb 250 ; energy
    defw 200 ; bounty in tenths of a credit
    defb $00 ; partially decoded property byte
    defb 40 ; visibility distance
    defw ShipPythonPirateVertices-ShipPythonPirateBlueprint
    defw ShipPythonPirateEdges-ShipPythonPirateBlueprint
    defw ShipPythonPirateFaces-ShipPythonPirateBlueprint
    defb $8C ; behaviour flags
    defb $00 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $80 ; partially decoded property byte
    defb 3 ; normal scaling exponent
assert $-ShipPythonPirateBlueprint = 23
ShipPythonPirateVertices:
    defb $00,$00,$E0,$1F,$10,$32,$00,$30,$30,$1F,$10,$54,$60,$00,$10,$3F,$FF,$FF,$60,$00,$10,$BF,$FF,$FF ; $6914
    defb $00,$30,$20,$3F,$54,$98,$00,$18,$70,$3F,$89,$CC,$30,$00,$70,$BF,$B8,$CC,$30,$00,$70,$3F,$A9,$CC ; $692C
    defb $00,$30,$30,$5F,$32,$76,$00,$30,$20,$7F,$76,$BA,$00,$18,$70,$7F,$BA,$CC ; $6944
assert $-ShipPythonPirateVertices = 66
ShipPythonPirateEdges:
    defb $1F,$00,$08,$32,$1F,$00,$03,$20,$1F,$00,$02,$31,$1F,$00,$01,$10 ; $6956
    defb $1F,$02,$04,$59,$1F,$01,$02,$51,$1F,$02,$08,$37,$1F,$01,$03,$40 ; $6966
    defb $1F,$03,$08,$62,$1F,$02,$09,$A7,$1F,$03,$04,$84,$1F,$03,$09,$B6 ; $6976
    defb $09,$03,$05,$88,$09,$03,$0A,$BB,$09,$02,$05,$99,$09,$02,$0A,$AA ; $6986
    defb $1F,$02,$07,$A9,$1F,$03,$06,$B8,$1F,$05,$06,$C8,$1F,$05,$07,$C9 ; $6996
    defb $1F,$07,$0A,$AC,$1F,$06,$0A,$CB,$1F,$04,$05,$98,$1F,$09,$0A,$BA ; $69A6
    defb $1F,$01,$04,$54,$1F,$08,$09,$76 ; $69B6
assert $-ShipPythonPirateEdges = 104
ShipPythonPirateFaces:
    defb $1B,$28,$0B,$9F,$1B,$28,$0B,$1F,$1B,$28,$0B,$DF,$1B,$28,$0B,$5F ; $69BE
    defb $13,$26,$00,$9F,$13,$26,$00,$1F,$13,$26,$00,$DF,$13,$26,$00,$5F ; $69CE
    defb $19,$25,$0B,$BF,$19,$25,$0B,$3F,$19,$25,$0B,$7F,$19,$25,$0B,$FF ; $69DE
    defb $00,$00,$70,$3F ; $69EE
assert $-ShipPythonPirateFaces = 52

; Blueprint ID 16: Sidewinder; original address $69F2.
ShipSidewinderBlueprint:
    defb $00 ; canister/commodity flags; low nibble is maximum canisters
    defb 65 ; target size
    defb $82 ; agility / rotation limit
    defb 10 ; vertices
    defb 15 ; edges
    defb 7 ; faces
    defb 37 ; maximum speed
    defb 70 ; energy
    defw 50 ; bounty in tenths of a credit
    defb $01 ; partially decoded property byte
    defb 20 ; visibility distance
    defw ShipSidewinderVertices-ShipSidewinderBlueprint
    defw ShipSidewinderEdges-ShipSidewinderBlueprint
    defw ShipSidewinderFaces-ShipSidewinderBlueprint
    defb $0C ; behaviour flags
    defb $02 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $00 ; partially decoded property byte
    defb 1 ; normal scaling exponent
assert $-ShipSidewinderBlueprint = 23
ShipSidewinderVertices:
    defb $20,$00,$24,$9F,$10,$54,$20,$00,$24,$1F,$20,$65,$40,$00,$1C,$3F,$32,$66,$40,$00,$1C,$BF,$31,$44 ; $6A09
    defb $00,$10,$1C,$3F,$10,$32,$00,$10,$1C,$7F,$43,$65,$0C,$06,$1C,$AF,$33,$33,$0C,$06,$1C,$2F,$33,$33 ; $6A21
    defb $0C,$06,$1C,$6C,$33,$33,$0C,$06,$1C,$EC,$33,$33 ; $6A39
assert $-ShipSidewinderVertices = 60
ShipSidewinderEdges:
    defb $1F,$00,$01,$50,$1F,$01,$02,$62,$1F,$01,$04,$20,$1F,$00,$04,$10 ; $6A45
    defb $1F,$00,$03,$41,$1F,$03,$04,$31,$1F,$02,$04,$32,$1F,$03,$05,$43 ; $6A55
    defb $1F,$02,$05,$63,$1F,$01,$05,$65,$1F,$00,$05,$54,$0F,$06,$07,$33 ; $6A65
    defb $0C,$07,$08,$33,$0C,$06,$09,$33,$0C,$08,$09,$33 ; $6A75
assert $-ShipSidewinderEdges = 60
ShipSidewinderFaces:
    defb $00,$20,$08,$1F,$0C,$2F,$06,$9F,$0C,$2F,$06,$1F,$00,$00,$70,$3F ; $6A81
    defb $0C,$2F,$06,$DF,$00,$20,$08,$5F,$0C,$2F,$06,$5F ; $6A91
assert $-ShipSidewinderFaces = 28

; Blueprint ID 0: Coriolis station; original address $6A9D.
ShipCoriolisStationBlueprint:
    defb $00 ; canister/commodity flags; low nibble is maximum canisters
    defb 160 ; target size
    defb $00 ; agility / rotation limit
    defb 16 ; vertices
    defb 28 ; edges
    defb 14 ; faces
    defb 0 ; maximum speed
    defb 240 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $06 ; partially decoded property byte
    defb 120 ; visibility distance
    defw ShipCoriolisStationVertices-ShipCoriolisStationBlueprint
    defw ShipCoriolisStationEdges-ShipCoriolisStationBlueprint
    defw ShipCoriolisStationFaces-ShipCoriolisStationBlueprint
    defb $00 ; behaviour flags
    defb $00 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $00 ; partially decoded property byte
    defb 0 ; normal scaling exponent
assert $-ShipCoriolisStationBlueprint = 23
ShipCoriolisStationVertices:
    defb $A0,$00,$A0,$1F,$10,$62,$00,$A0,$A0,$1F,$20,$83,$A0,$00,$A0,$9F,$30,$74,$00,$A0,$A0,$5F,$10,$54 ; $6AB4
    defb $A0,$A0,$00,$5F,$51,$A6,$A0,$A0,$00,$1F,$62,$B8,$A0,$A0,$00,$9F,$73,$C8,$A0,$A0,$00,$DF,$54,$97 ; $6ACC
    defb $A0,$00,$A0,$3F,$A6,$DB,$00,$A0,$A0,$3F,$B8,$DC,$A0,$00,$A0,$BF,$97,$DC,$00,$A0,$A0,$7F,$95,$DA ; $6AE4
    defb $0A,$1E,$A0,$5E,$00,$00,$0A,$1E,$A0,$1E,$00,$00,$0A,$1E,$A0,$9E,$00,$00,$0A,$1E,$A0,$DE,$00,$00 ; $6AFC
assert $-ShipCoriolisStationVertices = 96
ShipCoriolisStationEdges:
    defb $1F,$00,$03,$10,$1F,$00,$01,$20,$1F,$01,$02,$30,$1F,$02,$03,$40 ; $6B14
    defb $1F,$03,$04,$51,$1F,$00,$04,$61,$1F,$00,$05,$62,$1F,$05,$01,$82 ; $6B24
    defb $1F,$01,$06,$83,$1F,$02,$06,$73,$1F,$02,$07,$74,$1F,$03,$07,$54 ; $6B34
    defb $1F,$08,$0B,$DA,$1F,$08,$09,$DB,$1F,$09,$0A,$DC,$1F,$0A,$0B,$D9 ; $6B44
    defb $1F,$04,$0B,$A5,$1F,$04,$08,$A6,$1F,$05,$08,$B6,$1F,$05,$09,$B8 ; $6B54
    defb $1F,$06,$09,$C8,$1F,$06,$0A,$C7,$1F,$07,$0A,$97,$1F,$07,$0B,$95 ; $6B64
    defb $1E,$0C,$0D,$00,$1E,$0D,$0E,$00,$1E,$0E,$0F,$00,$1E,$0F,$0C,$00 ; $6B74
assert $-ShipCoriolisStationEdges = 112
ShipCoriolisStationFaces:
    defb $00,$00,$A0,$1F,$6B,$6B,$6B,$5F,$6B,$6B,$6B,$1F,$6B,$6B,$6B,$9F ; $6B84
    defb $6B,$6B,$6B,$DF,$00,$A0,$00,$5F,$A0,$00,$00,$1F,$A0,$00,$00,$9F ; $6B94
    defb $00,$A0,$00,$1F,$6B,$6B,$6B,$FF,$6B,$6B,$6B,$7F,$6B,$6B,$6B,$3F ; $6BA4
    defb $6B,$6B,$6B,$BF,$00,$00,$A0,$3F ; $6BB4
assert $-ShipCoriolisStationFaces = 56

; Blueprint ID 5: Splinter; original address $6BBC.
ShipSplinterBlueprint:
    defb $B0 ; canister/commodity flags; low nibble is maximum canisters
    defb 16 ; target size
    defb $00 ; agility / rotation limit
    defb 4 ; vertices
    defb 6 ; edges
    defb 4 ; faces
    defb 10 ; maximum speed
    defb 20 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $00 ; partially decoded property byte
    defb 10 ; visibility distance
    defw ShipSplinterVertices-ShipSplinterBlueprint
    defw ShipSplinterEdges-ShipSplinterBlueprint
    defw ShipSplinterFaces-ShipSplinterBlueprint
    defb $00 ; behaviour flags
    defb $05 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $1E ; partially decoded property byte
    defb 0 ; normal scaling exponent
assert $-ShipSplinterBlueprint = 23
ShipSplinterVertices:
    defb $18,$19,$10,$DF,$12,$33,$00,$0C,$0A,$3F,$02,$33,$0B,$06,$02,$5F,$01,$33,$0C,$2A,$07,$1F,$01,$22 ; $6BD3
assert $-ShipSplinterVertices = 24
ShipSplinterEdges:
    defb $1F,$00,$01,$23,$1F,$01,$02,$03,$1F,$02,$03,$01,$1F,$03,$00,$12 ; $6BEB
    defb $1F,$00,$02,$13,$1F,$03,$01,$02 ; $6BFB
assert $-ShipSplinterEdges = 24
ShipSplinterFaces:
    defb $B1,$0C,$94,$3F,$64,$19,$D5,$5F,$CA,$68,$22,$BF,$02,$33,$4A,$FF ; $6C03
assert $-ShipSplinterFaces = 16

; Blueprint ID 15: Thargoid; original address $6C13.
ShipThargoidBlueprint:
    defb $00 ; canister/commodity flags; low nibble is maximum canisters
    defb 99 ; target size
    defb $FF ; agility / rotation limit
    defb 20 ; vertices
    defb 26 ; edges
    defb 10 ; faces
    defb 39 ; maximum speed
    defb 240 ; energy
    defw 500 ; bounty in tenths of a credit
    defb $36 ; partially decoded property byte
    defb 55 ; visibility distance
    defw ShipThargoidVertices-ShipThargoidBlueprint
    defw ShipThargoidEdges-ShipThargoidBlueprint
    defw ShipThargoidFaces-ShipThargoidBlueprint
    defb $0C ; behaviour flags
    defb $02 ; partially decoded property byte
    defb 15 ; gun vertex
    defb $00 ; partially decoded property byte
    defb 8 ; normal scaling exponent
assert $-ShipThargoidBlueprint = 23
ShipThargoidVertices:
    defb $20,$30,$30,$5F,$40,$88,$20,$44,$00,$5F,$10,$44,$20,$30,$30,$7F,$21,$44,$20,$00,$44,$3F,$32,$44 ; $6C2A
    defb $20,$30,$30,$3F,$43,$55,$20,$44,$00,$1F,$54,$66,$20,$30,$30,$1F,$64,$77,$20,$00,$44,$1F,$74,$88 ; $6C42
    defb $18,$74,$74,$DF,$80,$99,$18,$A4,$00,$DF,$10,$99,$18,$74,$74,$FF,$21,$99,$18,$00,$A4,$BF,$32,$99 ; $6C5A
    defb $18,$74,$74,$BF,$53,$99,$18,$A4,$00,$9F,$65,$99,$18,$74,$74,$9F,$76,$99,$18,$00,$A4,$9F,$87,$99 ; $6C72
    defb $18,$40,$50,$9E,$99,$99,$18,$40,$50,$BE,$99,$99,$18,$40,$50,$FE,$99,$99,$18,$40,$50,$DE,$99,$99 ; $6C8A
assert $-ShipThargoidVertices = 120
ShipThargoidEdges:
    defb $1F,$00,$07,$84,$1F,$00,$01,$40,$1F,$01,$02,$41,$1F,$02,$03,$42 ; $6CA2
    defb $1F,$03,$04,$43,$1F,$04,$05,$54,$1F,$05,$06,$64,$1F,$06,$07,$74 ; $6CB2
    defb $1F,$00,$08,$80,$1F,$01,$09,$10,$1F,$02,$0A,$21,$1F,$03,$0B,$32 ; $6CC2
    defb $1F,$04,$0C,$53,$1F,$05,$0D,$65,$1F,$06,$0E,$76,$1F,$07,$0F,$87 ; $6CD2
    defb $1F,$08,$0F,$98,$1F,$08,$09,$90,$1F,$09,$0A,$91,$1F,$0A,$0B,$92 ; $6CE2
    defb $1F,$0B,$0C,$93,$1F,$0C,$0D,$95,$1F,$0D,$0E,$96,$1F,$0E,$0F,$97 ; $6CF2
    defb $1E,$10,$11,$99,$1E,$12,$13,$99 ; $6D02
assert $-ShipThargoidEdges = 104
ShipThargoidFaces:
    defb $67,$3C,$19,$5F,$67,$3C,$19,$7F,$67,$19,$3C,$7F,$67,$19,$3C,$3F ; $6D0A
    defb $40,$00,$00,$1F,$67,$3C,$19,$3F,$67,$3C,$19,$1F,$67,$19,$3C,$1F ; $6D1A
    defb $67,$19,$3C,$5F,$30,$00,$00,$9F ; $6D2A
assert $-ShipThargoidFaces = 40

IF SHIP_ADDER
    INCLUDE "adder.asm"
ELSE
; Blueprint ID 17: Krait; original address $6D32.
ShipKraitBlueprint:
    defb $01 ; canister/commodity flags; low nibble is maximum canisters
    defb 60 ; target size
    defb $6E ; agility / rotation limit
    defb 17 ; vertices
    defb 21 ; edges
    defb 6 ; faces
    defb 30 ; maximum speed
    defb 80 ; energy
    defw 100 ; bounty in tenths of a credit
    defb $00 ; partially decoded property byte
    defb 20 ; visibility distance
    defw ShipKraitVertices-ShipKraitBlueprint
    defw ShipKraitEdges-ShipKraitBlueprint
    defw ShipKraitFaces-ShipKraitBlueprint
    defb $8C ; behaviour flags
    defb $01 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $00 ; partially decoded property byte
    defb 1 ; normal scaling exponent
assert $-ShipKraitBlueprint = 23
ShipKraitVertices:
    defb $00,$00,$60,$1F,$01,$23,$00,$12,$30,$3F,$03,$45,$00,$12,$30,$7F,$12,$45,$5A,$00,$03,$3F,$01,$44 ; $6D49
    defb $5A,$00,$03,$BF,$23,$55,$5A,$00,$57,$1E,$01,$11,$5A,$00,$57,$9E,$23,$33,$00,$05,$35,$09,$00,$33 ; $6D61
    defb $00,$07,$26,$06,$00,$33,$12,$07,$13,$89,$33,$33,$12,$07,$13,$09,$00,$00,$12,$0B,$27,$28,$44,$44 ; $6D79
    defb $12,$0B,$27,$68,$44,$44,$24,$00,$1E,$28,$44,$44,$12,$0B,$27,$A8,$55,$55,$12,$0B,$27,$E8,$55,$55 ; $6D91
    defb $24,$00,$1E,$A8,$55,$55 ; $6DA9
assert $-ShipKraitVertices = 102
ShipKraitEdges:
    defb $1F,$00,$01,$03,$1F,$00,$02,$12,$1F,$00,$03,$01,$1F,$00,$04,$23 ; $6DAF
    defb $1F,$01,$04,$35,$1F,$04,$02,$25,$1F,$02,$03,$14,$1F,$03,$01,$04 ; $6DBF
    defb $1E,$03,$05,$01,$1E,$04,$06,$23,$08,$01,$02,$45,$09,$07,$0A,$00 ; $6DCF
    defb $06,$08,$0A,$00,$09,$07,$09,$33,$06,$08,$09,$33,$08,$0B,$0D,$44 ; $6DDF
    defb $08,$0D,$0C,$44,$07,$0C,$0B,$44,$07,$0E,$0F,$55,$08,$0F,$10,$55 ; $6DEF
    defb $08,$10,$0E,$55 ; $6DFF
assert $-ShipKraitEdges = 84
ShipKraitFaces:
    defb $03,$18,$03,$1F,$03,$18,$03,$5F,$03,$18,$03,$DF,$03,$18,$03,$9F ; $6E03
    defb $26,$00,$4D,$3F,$26,$00,$4D,$BF ; $6E13
assert $-ShipKraitFaces = 24

ENDIF
; Blueprint ID 8: Viper; original address $6E1B.
ShipViperBlueprint:
    defb $00 ; canister/commodity flags; low nibble is maximum canisters
    defb 75 ; target size
    defb $78 ; agility / rotation limit
    defb 15 ; vertices
    defb 20 ; edges
    defb 7 ; faces
    defb 32 ; maximum speed
    defb 140 ; energy
    defw 0 ; bounty in tenths of a credit
    defb $02 ; partially decoded property byte
    defb 23 ; visibility distance
    defw ShipViperVertices-ShipViperBlueprint
    defw ShipViperEdges-ShipViperBlueprint
    defw ShipViperFaces-ShipViperBlueprint
    defb $C2 ; behaviour flags
    defb $01 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $50 ; partially decoded property byte
    defb 0 ; normal scaling exponent
assert $-ShipViperBlueprint = 23
ShipViperVertices:
    defb $00,$00,$48,$1F,$21,$43,$00,$10,$18,$1E,$10,$22,$00,$10,$18,$5E,$43,$55,$30,$00,$18,$3F,$42,$66 ; $6E32
    defb $30,$00,$18,$BF,$31,$66,$18,$10,$18,$7E,$54,$66,$18,$10,$18,$FE,$35,$66,$18,$10,$18,$3F,$20,$66 ; $6E4A
    defb $18,$10,$18,$BF,$10,$66,$20,$00,$18,$B3,$66,$66,$20,$00,$18,$33,$66,$66,$08,$08,$18,$33,$66,$66 ; $6E62
    defb $08,$08,$18,$B3,$66,$66,$08,$08,$18,$F2,$66,$66,$08,$08,$18,$72,$66,$66 ; $6E7A
assert $-ShipViperVertices = 90
ShipViperEdges:
    defb $1F,$00,$03,$42,$1E,$00,$01,$21,$1E,$00,$02,$43,$1F,$00,$04,$31 ; $6E8C
    defb $1E,$01,$07,$20,$1E,$01,$08,$10,$1E,$02,$05,$54,$1E,$02,$06,$53 ; $6E9C
    defb $1F,$07,$08,$60,$1E,$05,$06,$65,$1F,$04,$08,$61,$1E,$04,$06,$63 ; $6EAC
    defb $1F,$03,$07,$62,$1E,$03,$05,$46,$13,$09,$0C,$66,$12,$09,$0D,$66 ; $6EBC
    defb $13,$0A,$0B,$66,$12,$0A,$0E,$66,$10,$0B,$0E,$66,$10,$0C,$0D,$66 ; $6ECC
assert $-ShipViperEdges = 80
ShipViperFaces:
    defb $00,$20,$00,$1F,$16,$21,$0B,$9F,$16,$21,$0B,$1F,$16,$21,$0B,$DF ; $6EDC
    defb $16,$21,$0B,$5F,$00,$20,$00,$5F,$00,$00,$30,$3F ; $6EEC
assert $-ShipViperFaces = 28

; Blueprint ID 18: Thargon; original address $6EF8.
ShipThargonBlueprint:
    defb $F0 ; canister/commodity flags; low nibble is maximum canisters
    defb 40 ; target size
    defb $78 ; agility / rotation limit
    defb 10 ; vertices
    defb 15 ; edges
    defb 7 ; faces
    defb 30 ; maximum speed
    defb 20 ; energy
    defw 50 ; bounty in tenths of a credit
    defb $01 ; partially decoded property byte
    defb 20 ; visibility distance
    defw ShipThargonVertices-ShipThargonBlueprint
    defw ShipThargonEdges-ShipThargonBlueprint
    defw ShipThargonFaces-ShipThargonBlueprint
    defb $04 ; behaviour flags
    defb $02 ; partially decoded property byte
    defb 0 ; gun vertex
    defb $64 ; partially decoded property byte
    defb 0 ; normal scaling exponent
assert $-ShipThargonBlueprint = 23
ShipThargonVertices:
    defb $09,$00,$28,$9F,$01,$55,$09,$26,$0C,$DF,$01,$22,$09,$18,$20,$FF,$02,$33,$09,$19,$20,$BF,$03,$44 ; $6F0F
    defb $09,$26,$0C,$9F,$04,$55,$09,$00,$08,$3F,$15,$66,$09,$0A,$0F,$7F,$12,$66,$09,$06,$1A,$7F,$23,$66 ; $6F27
    defb $09,$06,$1A,$3F,$34,$66,$09,$0A,$0F,$3F,$45,$66 ; $6F3F
assert $-ShipThargonVertices = 60
ShipThargonEdges:
    defb $1F,$00,$01,$01,$1F,$01,$02,$02,$1F,$02,$03,$03,$1F,$03,$04,$04 ; $6F4B
    defb $1F,$04,$00,$05,$1F,$00,$05,$15,$1F,$01,$06,$12,$1F,$02,$07,$23 ; $6F5B
    defb $1F,$03,$08,$43,$1F,$04,$09,$45,$1F,$05,$06,$61,$1F,$06,$07,$61 ; $6F6B
    defb $1F,$07,$08,$63,$1F,$08,$09,$64,$1F,$09,$05,$65 ; $6F7B
assert $-ShipThargonEdges = 60
ShipThargonFaces:
    defb $24,$00,$00,$9F,$14,$05,$07,$5F,$2E,$2A,$0E,$7F,$24,$00,$68,$3F ; $6F87
    defb $2E,$2A,$0E,$3F,$14,$05,$07,$1F,$24,$00,$00,$1F ; $6F97
assert $-ShipThargonFaces = 28

ShipGeometryEnd:
IF SHIP_ADDER
    INCLUDE "text-dispatch-second.asm"
ELSE
    INCLUDE "text-dispatch-first.asm"
    INCLUDE "text-dispatch-second.asm"
ENDIF

ShipBlueprintsAndDispatchTablesEnd:
defc ShipBlueprintsAndDispatchTablesSize = ShipBlueprintsAndDispatchTablesEnd - ShipBlueprintsAndDispatchTables
assert ShipBlueprintsAndDispatchTablesSize = 3712
IF !SHIP_ADDER
assert L_640A-ShipBlueprintsAndDispatchTables = $640A-$6180
assert L_6FA3-ShipBlueprintsAndDispatchTables = $6FA3-$6180
assert L_6FBF-ShipBlueprintsAndDispatchTables = $6FBF-$6180
ENDIF
